import type { Business, Category, City, Listing } from "../types/deals";

export const demoNotice =
  "Demo scaffolding only. These example listings are not production partners or live bookable inventory.";

export const demoCities: City[] = [
  {
    active: true,
    comingSoon: false,
    country: "US",
    description: "A starter market for testing date nights, group plans, family ideas, and last-minute local deals.",
    heroImageUrl: null,
    id: "miami",
    name: "Miami",
    slug: "miami",
    state: "FL",
    timezone: "America/New_York"
  },
  {
    active: true,
    comingSoon: false,
    country: "US",
    description: "Demo activity discovery for classes, deals, group plans, and last-minute local experiences.",
    heroImageUrl: null,
    id: "los-angeles",
    name: "Los Angeles",
    slug: "los-angeles",
    state: "CA",
    timezone: "America/Los_Angeles"
  },
  {
    active: true,
    comingSoon: false,
    country: "US",
    description: "Local plans for date nights, family weekends, events, and spontaneous fun.",
    heroImageUrl: null,
    id: "new-york",
    name: "New York",
    slug: "new-york",
    state: "NY",
    timezone: "America/New_York"
  },
  {
    active: true,
    comingSoon: false,
    country: "US",
    description: "A fast-growing test market for activities, classes, live events, and local deals.",
    heroImageUrl: null,
    id: "austin",
    name: "Austin",
    slug: "austin",
    state: "TX",
    timezone: "America/Chicago"
  },
  {
    active: true,
    comingSoon: false,
    country: "US",
    description: "Coastal plans, family activities, outdoor ideas, and local classes.",
    heroImageUrl: null,
    id: "san-diego",
    name: "San Diego",
    slug: "san-diego",
    state: "CA",
    timezone: "America/Los_Angeles"
  }
];

export const demoCategories: Category[] = [
  { accentColor: "#fb7185", active: true, description: "Date ideas, romantic plans, and low-pressure couples activities.", icon: "Heart", id: "date-night", name: "Date Night", slug: "date-night", sortOrder: 1 },
  { accentColor: "#bef264", active: true, description: "Group-friendly ideas that are easy to agree on.", icon: "Users", id: "friends", name: "Friends", slug: "friends", sortOrder: 2 },
  { accentColor: "#fbbf24", active: true, description: "Kid-friendly and parent-friendly local activities.", icon: "Baby", id: "family", name: "Family", slug: "family", sortOrder: 3 },
  { accentColor: "#facc15", active: true, description: "Play spaces, classes, and weekend plans for kids.", icon: "Puzzle", id: "kids", name: "Kids", slug: "kids", sortOrder: 4 },
  { accentColor: "#a78bfa", active: true, description: "Fitness studios, movement classes, and active plans.", icon: "Dumbbell", id: "fitness", name: "Fitness", slug: "fitness", sortOrder: 5 },
  { accentColor: "#fb7185", active: true, description: "Workshops, pottery, dance, cooking, and hands-on experiences.", icon: "Palette", id: "creative", name: "Creative", slug: "creative", sortOrder: 6 },
  { accentColor: "#f97316", active: true, description: "Food events, tasting plans, coffee walks, and casual bites.", icon: "Utensils", id: "food-drink", name: "Food & Drink", slug: "food-drink", sortOrder: 7 },
  { accentColor: "#c084fc", active: true, description: "Comedy, music, open mics, dancing, and evening plans.", icon: "Mic", id: "nightlife", name: "Nightlife", slug: "nightlife", sortOrder: 8 },
  { accentColor: "#22d3ee", active: true, description: "Parks, walks, waterfront ideas, tours, and active outdoor plans.", icon: "Trees", id: "outdoor", name: "Outdoor", slug: "outdoor", sortOrder: 9 },
  { accentColor: "#34d399", active: true, description: "Yoga, spa, wellness, low-energy, and reset plans.", icon: "Leaf", id: "wellness", name: "Wellness", slug: "wellness", sortOrder: 10 },
  { accentColor: "#38bdf8", active: true, description: "Trial classes, learning experiences, and skill-building activities.", icon: "GraduationCap", id: "classes", name: "Classes", slug: "classes", sortOrder: 11 },
  { accentColor: "#f472b6", active: true, description: "Comedy nights, pop-ups, workshops, and time-specific events.", icon: "Calendar", id: "events", name: "Events", slug: "events", sortOrder: 12 }
];

export const demoBusinesses: Business[] = [
  {
    addressLine1: "Demo address hidden",
    addressLine2: null,
    categories: ["date-night", "creative", "classes"],
    cityId: "miami",
    country: "US",
    description: "Demo pottery studio profile for local deal UX testing.",
    email: "demo-clay@gofunmotion.test",
    id: "demo-clay-house",
    instagram: null,
    isDemo: true,
    latitude: null,
    logoUrl: null,
    longitude: null,
    name: "Demo Clay House",
    ownerIds: ["demo-business-owner"],
    phone: null,
    photos: [],
    postalCode: "00000",
    slug: "demo-clay-house",
    state: "FL",
    status: "approved",
    verificationStatus: "unverified",
    website: null
  },
  {
    addressLine1: "Demo address hidden",
    addressLine2: null,
    categories: ["friends", "events", "nightlife"],
    cityId: "austin",
    country: "US",
    description: "Demo escape-room and event profile for last-minute slot testing.",
    email: "demo-lockbox@gofunmotion.test",
    id: "demo-lockbox-games",
    instagram: null,
    isDemo: true,
    latitude: null,
    logoUrl: null,
    longitude: null,
    name: "Demo Lockbox Games",
    ownerIds: ["demo-business-owner"],
    phone: null,
    photos: [],
    postalCode: "00000",
    slug: "demo-lockbox-games",
    state: "TX",
    status: "approved",
    verificationStatus: "unverified",
    website: null
  },
  {
    addressLine1: "Demo address hidden",
    addressLine2: null,
    categories: ["family", "kids"],
    cityId: "san-diego",
    country: "US",
    description: "Demo indoor play profile for family plan testing.",
    email: "demo-play@gofunmotion.test",
    id: "demo-indoor-play-lab",
    instagram: null,
    isDemo: true,
    latitude: null,
    logoUrl: null,
    longitude: null,
    name: "Demo Indoor Play Lab",
    ownerIds: ["demo-business-owner"],
    phone: null,
    photos: [],
    postalCode: "00000",
    slug: "demo-indoor-play-lab",
    state: "CA",
    status: "approved",
    verificationStatus: "unverified",
    website: null
  }
];

export const demoListings: Listing[] = [
  {
    approvalStatus: "approved",
    availableDays: ["today", "tonight", "weekend"],
    availableFrom: null,
    availableSlots: ["6:00 PM", "7:30 PM"],
    availableUntil: null,
    bookingMode: "request",
    bookingUrl: null,
    budgetTier: "under50",
    businessId: "demo-clay-house",
    businessName: "Demo Clay House",
    cancellationNote: "Demo cancellation note. Partner terms will be configured when real businesses are approved.",
    capacity: 12,
    categoryIds: ["date-night", "creative", "classes"],
    cityId: "miami",
    cityName: "Miami",
    clickCount: 0,
    currency: "USD",
    description: "A hands-on pottery night designed for a relaxed date or creative friend hang. Includes guided wheel time and a simple glaze option.",
    discountPercent: 25,
    durationMinutes: 90,
    email: null,
    featured: true,
    groupSize: "2-8",
    groupTypes: ["date", "friends"],
    id: "pottery-date-night-demo",
    images: [],
    indoorOutdoor: "indoor",
    isDemo: true,
    listingType: "class",
    originalPrice: 60,
    ownerIds: ["demo-business-owner"],
    phone: null,
    price: 45,
    promoted: false,
    requestCount: 0,
    saveCount: 0,
    shortDescription: "Creative indoor date night with a demo 25% off deal.",
    slug: "pottery-date-night-demo",
    status: "published",
    terms: "Demo terms only. No live purchase or booking is available.",
    title: "Pottery Date Night - 25% Off",
    vibeTags: ["romantic", "creative", "chill", "rainy-day"],
    viewCount: 0,
    whyItFits: "Hands-on, easy to talk during, and clear enough for a last-minute plan."
  },
  {
    approvalStatus: "approved",
    availableDays: ["today", "tonight", "weekend"],
    availableFrom: null,
    availableSlots: ["8:00 PM", "9:15 PM"],
    availableUntil: null,
    bookingMode: "request",
    bookingUrl: null,
    budgetTier: "under25",
    businessId: "demo-lockbox-games",
    businessName: "Demo Lockbox Games",
    cancellationNote: "Demo cancellation note. Real partner policies will appear on approved listings.",
    capacity: 8,
    categoryIds: ["friends", "events"],
    cityId: "austin",
    cityName: "Austin",
    clickCount: 0,
    currency: "USD",
    description: "A short escape-room slot for groups that want an activity with a clear start, finish, and shared story afterward.",
    discountPercent: 30,
    durationMinutes: 60,
    email: null,
    featured: true,
    groupSize: "2-6",
    groupTypes: ["friends", "date"],
    id: "escape-room-last-minute-demo",
    images: [],
    indoorOutdoor: "indoor",
    isDemo: true,
    listingType: "deal",
    originalPrice: 32,
    ownerIds: ["demo-business-owner"],
    phone: null,
    price: 22,
    promoted: true,
    requestCount: 0,
    saveCount: 0,
    shortDescription: "Last-minute indoor group plan with a demo discount.",
    slug: "escape-room-last-minute-demo",
    status: "published",
    terms: "Demo terms only. No live purchase or booking is available.",
    title: "Escape Room - Last-Minute Slot",
    vibeTags: ["active", "social", "adventurous", "rainy-day"],
    viewCount: 0,
    whyItFits: "Good for friends who need a decision fast and want something more memorable than dinner."
  },
  {
    approvalStatus: "approved",
    availableDays: ["tomorrow", "weekend"],
    availableFrom: null,
    availableSlots: ["10:00 AM", "1:00 PM", "3:00 PM"],
    availableUntil: null,
    bookingMode: "request",
    bookingUrl: null,
    budgetTier: "under25",
    businessId: "demo-indoor-play-lab",
    businessName: "Demo Indoor Play Lab",
    cancellationNote: "Demo cancellation note. Approved partners will provide the real policy.",
    capacity: 30,
    categoryIds: ["family", "kids"],
    cityId: "san-diego",
    cityName: "San Diego",
    clickCount: 0,
    currency: "USD",
    description: "A simple indoor play session for families who need a weather-proof plan and enough structure to make the day easier.",
    discountPercent: 20,
    durationMinutes: 120,
    email: null,
    featured: false,
    groupSize: "2-6",
    groupTypes: ["family", "kids"],
    id: "kids-indoor-play-weekend-demo",
    images: [],
    indoorOutdoor: "indoor",
    isDemo: true,
    listingType: "activity",
    originalPrice: 25,
    ownerIds: ["demo-business-owner"],
    phone: null,
    price: 20,
    promoted: false,
    requestCount: 0,
    saveCount: 0,
    shortDescription: "Weekend family activity with a demo kids deal.",
    slug: "kids-indoor-play-weekend-demo",
    status: "published",
    terms: "Demo terms only. No live purchase or booking is available.",
    title: "Kids Indoor Play - Weekend",
    vibeTags: ["family-friendly", "low-energy", "rainy-day"],
    viewCount: 0,
    whyItFits: "Indoor, predictable, and built around kids having room to move."
  },
  {
    approvalStatus: "approved",
    availableDays: ["today", "tonight"],
    availableFrom: null,
    availableSlots: ["7:00 PM", "8:30 PM"],
    availableUntil: null,
    bookingMode: "request",
    bookingUrl: null,
    budgetTier: "under50",
    businessId: "demo-lockbox-games",
    businessName: "Demo Lockbox Games",
    cancellationNote: "Demo cancellation note. Real partner policies will appear on approved listings.",
    capacity: 16,
    categoryIds: ["date-night", "friends", "outdoor"],
    cityId: "los-angeles",
    cityName: "Los Angeles",
    clickCount: 0,
    currency: "USD",
    description: "A compact mini golf plan for pairs or small groups who want light competition without a full-night commitment.",
    discountPercent: 15,
    durationMinutes: 75,
    email: null,
    featured: false,
    groupSize: "2-8",
    groupTypes: ["date", "friends", "family"],
    id: "mini-golf-friends-plan-demo",
    images: [],
    indoorOutdoor: "either",
    isDemo: true,
    listingType: "activity",
    originalPrice: 28,
    ownerIds: ["demo-business-owner"],
    phone: null,
    price: 24,
    promoted: false,
    requestCount: 0,
    saveCount: 0,
    shortDescription: "Easy group activity with a demo last-minute price.",
    slug: "mini-golf-friends-plan-demo",
    status: "published",
    terms: "Demo terms only. No live purchase or booking is available.",
    title: "Mini Golf - Friends Plan",
    vibeTags: ["social", "active", "chill", "romantic"],
    viewCount: 0,
    whyItFits: "Casual, social, and works even when nobody wants to over-plan."
  },
  {
    approvalStatus: "approved",
    availableDays: ["today", "tomorrow", "weekend"],
    availableFrom: null,
    availableSlots: ["6:30 PM", "8:00 PM"],
    availableUntil: null,
    bookingMode: "request",
    bookingUrl: null,
    budgetTier: "under25",
    businessId: "demo-clay-house",
    businessName: "Demo Clay House",
    cancellationNote: "Demo cancellation note. Real partner policies will appear on approved listings.",
    capacity: 20,
    categoryIds: ["classes", "fitness", "nightlife"],
    cityId: "new-york",
    cityName: "New York",
    clickCount: 0,
    currency: "USD",
    description: "A beginner-friendly salsa trial class for people who want a social plan with movement and music.",
    discountPercent: null,
    durationMinutes: 60,
    email: null,
    featured: true,
    groupSize: "1-20",
    groupTypes: ["solo", "date", "friends"],
    id: "salsa-trial-class-demo",
    images: [],
    indoorOutdoor: "indoor",
    isDemo: true,
    listingType: "class",
    originalPrice: null,
    ownerIds: ["demo-business-owner"],
    phone: null,
    price: 10,
    promoted: false,
    requestCount: 0,
    saveCount: 0,
    shortDescription: "Beginner dance trial class with demo pricing.",
    slug: "salsa-trial-class-demo",
    status: "published",
    terms: "Demo terms only. No live purchase or booking is available.",
    title: "Dance Trial Class - $10",
    vibeTags: ["social", "active", "adventurous"],
    viewCount: 0,
    whyItFits: "It gives solo visitors, dates, and friends a clear social activity with a low commitment."
  }
];
