// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

abstract final class AppState {
  static const activeCity = ffai.ProjectAppStateFieldHandle(
    name: "activeCity",
    key: "xra2thyf",
    typeName: "String",
    persisted: true,
  );
  static const planPersona = ffai.ProjectAppStateFieldHandle(
    name: "planPersona",
    key: "zb8f5okl",
    typeName: "String",
    persisted: true,
  );
  static const all = <ffai.ProjectAppStateFieldHandle>[activeCity, planPersona];
}
