// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'components/deal_card.dart' show DealCardComponentHandle;
import 'components/empty_state.dart' show EmptyStateComponentHandle;
import 'components/plan_step_card.dart' show PlanStepCardComponentHandle;
import 'components/section_header.dart' show SectionHeaderComponentHandle;

abstract final class Components {
  static final dealCard = DealCardComponentHandle();
  static final emptyState = EmptyStateComponentHandle();
  static final planStepCard = PlanStepCardComponentHandle();
  static final sectionHeader = SectionHeaderComponentHandle();
  static final all = <ffai.ProjectComponentHandle>[
    dealCard,
    emptyState,
    planStepCard,
    sectionHeader,
  ];
}
