// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;
import 'pages/admin_page.dart' show adminPageHandle;
import 'pages/deal_detail_page.dart' show dealDetailPageHandle;
import 'pages/deals_page.dart' show dealsPageHandle;
import 'pages/discover_page.dart' show discoverPageHandle;
import 'pages/find_plan_page.dart' show findPlanPageHandle;
import 'pages/partner_apply_page.dart' show partnerApplyPageHandle;
import 'pages/partner_dashboard_page.dart' show partnerDashboardPageHandle;
import 'pages/partner_deal_editor_page.dart' show partnerDealEditorPageHandle;
import 'pages/partner_page.dart' show partnerPageHandle;
import 'pages/profile_page.dart' show profilePageHandle;
import 'pages/reset_password_page.dart' show resetPasswordPageHandle;
import 'pages/saved_page.dart' show savedPageHandle;
import 'pages/sign_in_page.dart' show signInPageHandle;
import 'pages/splash_page.dart' show splashPageHandle;
import 'pages/waitlist_page.dart' show waitlistPageHandle;

abstract final class Pages {
  static final adminPage = adminPageHandle;
  static final dealDetailPage = dealDetailPageHandle;
  static final dealsPage = dealsPageHandle;
  static final discoverPage = discoverPageHandle;
  static final findPlanPage = findPlanPageHandle;
  static final partnerApplyPage = partnerApplyPageHandle;
  static final partnerDashboardPage = partnerDashboardPageHandle;
  static final partnerDealEditorPage = partnerDealEditorPageHandle;
  static final partnerPage = partnerPageHandle;
  static final profilePage = profilePageHandle;
  static final resetPasswordPage = resetPasswordPageHandle;
  static final savedPage = savedPageHandle;
  static final signInPage = signInPageHandle;
  static final splashPage = splashPageHandle;
  static final waitlistPage = waitlistPageHandle;
  static final all = <ffai.ProjectPageHandle>[
    adminPage,
    dealDetailPage,
    dealsPage,
    discoverPage,
    findPlanPage,
    partnerApplyPage,
    partnerDashboardPage,
    partnerDealEditorPage,
    partnerPage,
    profilePage,
    resetPasswordPage,
    savedPage,
    signInPage,
    splashPage,
    waitlistPage,
  ];
}
