// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final adminReviewsPageHandle = ffai.ProjectPageHandle<AdminReviewsPageParams, AdminReviewsPageState>(
  name: "AdminReviewsPage",
  key: "Scaffold_k6dvlzux",
  route: "admin-reviews",
  params: const AdminReviewsPageParams(),
  state: const AdminReviewsPageState(),
  widgets: AdminReviewsPageWidgets.tree,
);

final class AdminReviewsPageParams {
  const AdminReviewsPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "rq9e68l6",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "jxew1wlc",
        typeName: "String",
      );
}

final class AdminReviewsPageState {
  const AdminReviewsPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "cj89g1ey",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "5g6iaa3f",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "n4ng7q3a",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "3kkkufp7",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "byoi2h8i",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "sztt0hcc",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "a0glz88v",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "jvjkn6wd",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "g5y0ergu",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "p10gj8j0",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "ag5az8d5",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "6n1jev5y",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "v52znnmn",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "u9lv3jsc",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "11nn1pfd",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "dhqrsqa0",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "vljqmtrn",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "ps086wid",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "4c77hj91",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "h2ol6zcg",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "qbufb82s",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "tix2hpup",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "3scm1bre",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "ro2h6xxl",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "u1ulhtk6",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "8qhbv7gc",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "1ynf2hqq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "xh5tz4ya",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "msyykptv",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "v31nf53q",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "nqexc8eu",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "d4b51klq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "uxooxadf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "6uilcuuq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "tdv7ce33",
        typeName: "String",
      );
}

abstract final class AdminReviewsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_k6dvlzux",
      type: "Scaffold",
      path: "AdminReviewsPage",
      name: "AdminReviewsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_pi8uzsan",
            type: "AppBar",
            path: "AdminReviewsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_vtoe55w3",
                  type: "Text",
                  path: "AdminReviewsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Review moderation",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_mtfgdl8j",
            type: "Container",
            path: "AdminReviewsPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_pm3gdq0s",
                type: "Column",
                path: "AdminReviewsPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_cktqksrd",
                    type: "ProgressBar",
                    path: "AdminReviewsPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_6z44xy2e",
                    type: "ProgressBar",
                    path: "AdminReviewsPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_nx2e1d8q",
                    type: "Text",
                    path: "AdminReviewsPage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_s6jxpkaf",
                    type: "Column",
                    path: "AdminReviewsPage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_4whm2an6",
                        type: "Column",
                        path: "AdminReviewsPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_35zx5830",
                            type: "Button",
                            path: "AdminReviewsPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_ifavpzbe",
                        type: "Button",
                        path: "AdminReviewsPage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_l0no2idg",
                    type: "Column",
                    path: "AdminReviewsPage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_m4zhavoa",
                        type: "Icon",
                        path: "AdminReviewsPage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_j4pm7ppb",
                        type: "Text",
                        path: "AdminReviewsPage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_8d5ty13j",
                        type: "Button",
                        path: "AdminReviewsPage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_btfprnxf",
                    type: "Column",
                    path: "AdminReviewsPage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_4jcidudd",
                        type: "Row",
                        path: "AdminReviewsPage.body[0].children[0].children[5].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_tejwmu06",
                            type: "Text",
                            path: "AdminReviewsPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "Text",
                            text: "Records",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_i7izfv9a",
                            type: "IconButton",
                            path: "AdminReviewsPage.body[0].children[0].children[5].children[0].children[1]",
                            name: "RefreshWorkspaceList",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_tgnkifop",
                        type: "Container",
                        path: "AdminReviewsPage.body[0].children[0].children[5].children[1]",
                        name: "WorkspaceEmptyState",
                        componentName: "WorkspaceEmptyState",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_aeebtmx9",
                        type: "ListView",
                        path: "AdminReviewsPage.body[0].children[0].children[5].children[2]",
                        name: "WorkspaceRecordList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_r1njrjam",
                            type: "Container",
                            path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_gv8mo68j",
                                type: "Column",
                                path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_0rwifkgi",
                                    type: "Row",
                                    path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[0]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_runpdty6",
                                        type: "Text",
                                        path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[0].children[0]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_5m9lakej",
                                        type: "Icon",
                                        path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_1auwrvus",
                                    type: "Text",
                                    path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_nngzbe48",
                                    type: "Text",
                                    path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[2]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_nkyeu9tz",
                                    type: "Text",
                                    path: "AdminReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[3]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_mxql1mjk",
                        type: "Row",
                        path: "AdminReviewsPage.body[0].children[0].children[5].children[3]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_6k7gbdcb",
                            type: "Button",
                            path: "AdminReviewsPage.body[0].children[0].children[5].children[3].children[0]",
                            name: "Button",
                            text: "First page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_efkzqi9t",
                            type: "Button",
                            path: "AdminReviewsPage.body[0].children[0].children[5].children[3].children[1]",
                            name: "Button",
                            text: "Next page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

