// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final adminPageHandle = ffai.ProjectPageHandle<AdminPageParams, AdminPageState>(
  name: "AdminPage",
  key: "Scaffold_zl253w6v",
  route: "admin",
  params: const AdminPageParams(),
  state: const AdminPageState(),
  widgets: AdminPageWidgets.tree,
);

final class AdminPageParams {
  const AdminPageParams();
}

final class AdminPageState {
  const AdminPageState();
  ffai.ProjectStateFieldHandle get adminListings =>
      const ffai.ProjectStateFieldHandle(
        name: "adminListings",
        key: "im10vq3r",
        typeName: "List<Document<listings>>",
      );
  ffai.ProjectStateFieldHandle get applications =>
      const ffai.ProjectStateFieldHandle(
        name: "applications",
        key: "yqgn4ph2",
        typeName: "List<Document<partnerApplications>>",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "yh0ytmx3",
        typeName: "Boolean",
      );
}

abstract final class AdminPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_zl253w6v",
      type: "Scaffold",
      path: "AdminPage",
      name: "AdminPage",
      triggers: const <String>["ON_INIT_STATE"],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_u0h565h5",
            type: "AppBar",
            path: "AdminPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_zrv6binx",
                  type: "Text",
                  path: "AdminPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Admin",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_9vqdfk15",
            type: "Column",
            path: "AdminPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_bh4mhw9y",
                type: "Container",
                path: "AdminPage.body[0].children[0]",
                name: "SectionHeader",
                componentName: "SectionHeader",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_hblid0km",
                type: "Container",
                path: "AdminPage.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_1ps23pr1",
                    type: "Container",
                    path: "AdminPage.body[0].children[1].children[0]",
                    name: "EmptyState",
                    componentName: "EmptyState",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_sh90m1dy",
                type: "ListView",
                path: "AdminPage.body[0].children[2]",
                name: "AdminApplicationsList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_7men1x5s",
                    type: "Container",
                    path: "AdminPage.body[0].children[2].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_br0srpu4",
                        type: "Column",
                        path:
                            "AdminPage.body[0].children[2].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_x9zwxfu9",
                            type: "Text",
                            path:
                                "AdminPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_5pp30jos",
                            type: "Text",
                            path:
                                "AdminPage.body[0].children[2].children[0].children[0].children[1]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_sycpvvmh",
                            type: "Text",
                            path:
                                "AdminPage.body[0].children[2].children[0].children[0].children[2]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_7l5f3wbr",
                            type: "Row",
                            path:
                                "AdminPage.body[0].children[2].children[0].children[0].children[3]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Button_kpnez1rm",
                                type: "Button",
                                path:
                                    "AdminPage.body[0].children[2].children[0].children[0].children[3].children[0]",
                                name: "Button",
                                text: "Approve",
                                triggers: const <String>["ON_TAP"],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_j78gs2uu",
                                type: "Button",
                                path:
                                    "AdminPage.body[0].children[2].children[0].children[0].children[3].children[1]",
                                name: "Button",
                                text: "Needs Info",
                                triggers: const <String>["ON_TAP"],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_8x5zxx30",
                type: "Container",
                path: "AdminPage.body[0].children[3]",
                name: "SectionHeader",
                componentName: "SectionHeader",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_20dqsmgf",
                type: "ListView",
                path: "AdminPage.body[0].children[4]",
                name: "AdminListingsList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_ca6dr1za",
                    type: "Container",
                    path: "AdminPage.body[0].children[4].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_hymjndj3",
                        type: "Column",
                        path:
                            "AdminPage.body[0].children[4].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_res0bih2",
                            type: "Text",
                            path:
                                "AdminPage.body[0].children[4].children[0].children[0].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_9n2hl67g",
                            type: "Text",
                            path:
                                "AdminPage.body[0].children[4].children[0].children[0].children[1]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Row_fvb3s7bu",
                            type: "Row",
                            path:
                                "AdminPage.body[0].children[4].children[0].children[0].children[2]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Button_6hu39yl6",
                                type: "Button",
                                path:
                                    "AdminPage.body[0].children[4].children[0].children[0].children[2].children[0]",
                                name: "Button",
                                text: "Publish",
                                triggers: const <String>["ON_TAP"],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_8nao7dig",
                                type: "Button",
                                path:
                                    "AdminPage.body[0].children[4].children[0].children[0].children[2].children[1]",
                                name: "Button",
                                text: "Hide",
                                triggers: const <String>["ON_TAP"],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
