// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final adminBookingDetailPageHandle = ffai.ProjectPageHandle<AdminBookingDetailPageParams, AdminBookingDetailPageState>(
  name: "AdminBookingDetailPage",
  key: "Scaffold_btwlt4sl",
  route: "admin-booking-detail",
  params: const AdminBookingDetailPageParams(),
  state: const AdminBookingDetailPageState(),
  widgets: AdminBookingDetailPageWidgets.tree,
);

final class AdminBookingDetailPageParams {
  const AdminBookingDetailPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "y36fvs30",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "8kd1v0qi",
        typeName: "String",
      );
}

final class AdminBookingDetailPageState {
  const AdminBookingDetailPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "sda6qgw9",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "3zi4egc3",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "thtg63eu",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "q1wkojcn",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "6nhzwv71",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "azb1innf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "id3guged",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "ulg7qu6e",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "rhbxscxo",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "meg0lkqt",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "qqqh6z92",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "pewxn7bn",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "0lvvr0am",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "w9dbmmbf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "pt1qk73k",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "8qy4q25e",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "8cfypazg",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "drxlaz83",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "s64j5x1g",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "61f9k625",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "8qrw9h8j",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "9qe1if4t",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "9z31q5pu",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "avqo3m16",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "4h74u7fj",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "lwob2774",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "ackwjd8s",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "v4iub199",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "y955lnn3",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "56xqb0ai",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "kwq7ublq",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "i5r0cjjl",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "9oyww99c",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "rsceu4wd",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "zxhue0fx",
        typeName: "String",
      );
}

abstract final class AdminBookingDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_btwlt4sl",
      type: "Scaffold",
      path: "AdminBookingDetailPage",
      name: "AdminBookingDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_zsr9866s",
            type: "AppBar",
            path: "AdminBookingDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_fvaesc3a",
                  type: "Text",
                  path: "AdminBookingDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Booking overview",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_mqnngeyk",
            type: "Container",
            path: "AdminBookingDetailPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_35ecvmvq",
                type: "Column",
                path: "AdminBookingDetailPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_i6m2mvhp",
                    type: "ProgressBar",
                    path: "AdminBookingDetailPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_gogwv9sf",
                    type: "ProgressBar",
                    path: "AdminBookingDetailPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_3u8cn7tg",
                    type: "Text",
                    path: "AdminBookingDetailPage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_0265zno5",
                    type: "Column",
                    path: "AdminBookingDetailPage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_8krqoyjo",
                        type: "Column",
                        path: "AdminBookingDetailPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_e3ouj96j",
                            type: "Button",
                            path: "AdminBookingDetailPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_53126lcy",
                        type: "Button",
                        path: "AdminBookingDetailPage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_ks7omts4",
                    type: "Column",
                    path: "AdminBookingDetailPage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_ftxgxd76",
                        type: "Icon",
                        path: "AdminBookingDetailPage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_rrq3rr2x",
                        type: "Text",
                        path: "AdminBookingDetailPage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_sgjq7tzo",
                        type: "Button",
                        path: "AdminBookingDetailPage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_zuo77ubz",
                    type: "Column",
                    path: "AdminBookingDetailPage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_2vc801kn",
                        type: "Text",
                        path: "AdminBookingDetailPage.body[0].children[0].children[5].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_ymzrwyjn",
                        type: "Text",
                        path: "AdminBookingDetailPage.body[0].children[0].children[5].children[1]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ketjy0g7",
                        type: "Container",
                        path: "AdminBookingDetailPage.body[0].children[0].children[5].children[2]",
                        name: "WorkspaceStatusBadge",
                        componentName: "WorkspaceStatusBadge",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_hvy42xzd",
                        type: "Text",
                        path: "AdminBookingDetailPage.body[0].children[0].children[5].children[3]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_w8d6u52u",
                        type: "Container",
                        path: "AdminBookingDetailPage.body[0].children[0].children[5].children[4]",
                        name: "WorkspaceMenuRow",
                        componentName: "WorkspaceMenuRow",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

