// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final customerOnboardingPageHandle = ffai.ProjectPageHandle<CustomerOnboardingPageParams, CustomerOnboardingPageState>(
  name: "CustomerOnboardingPage",
  key: "Scaffold_ty204xrm",
  route: "customer-onboarding",
  params: const CustomerOnboardingPageParams(),
  state: const CustomerOnboardingPageState(),
  widgets: CustomerOnboardingPageWidgets.tree,
);

final class CustomerOnboardingPageParams {
  const CustomerOnboardingPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "nqlq3aag",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "dpuxhgb8",
        typeName: "String",
      );
  ffai.ProjectParamHandle get returnPage =>
      const ffai.ProjectParamHandle(
        name: "returnPage",
        key: "hdbgvgsv",
        typeName: "String",
      );
}

final class CustomerOnboardingPageState {
  const CustomerOnboardingPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "10xaxs60",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "6g35n8yy",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "jhf8w9ga",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "aihu174w",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "epbipfrh",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "xlji689r",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "qdmyv4ow",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "utr7xvrh",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "xmimahe6",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "uqils778",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "9gor43lu",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "mxvqq406",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "k6upskug",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "sd02uilw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "zce8u4px",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "je1pun7n",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "d3e835kv",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "a3trotbe",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "0oaapmn0",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "4k4059yb",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "zmzdo3mg",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "6wjymwt3",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "z96kwgma",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "0eoukz15",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "kf0b4f5t",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "dc1gupvy",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "vp7j7kro",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "bqd28dvz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "tcyxyngd",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "ps3ap8uf",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "umrfit8w",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "qyoji8yq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "ocmy8t9v",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "69yttky5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "6sxvc0iq",
        typeName: "String",
      );
}

abstract final class CustomerOnboardingPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ty204xrm",
      type: "Scaffold",
      path: "CustomerOnboardingPage",
      name: "CustomerOnboardingPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_x9rjdpmy",
            type: "AppBar",
            path: "CustomerOnboardingPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_e13rawu0",
                  type: "Text",
                  path: "CustomerOnboardingPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Your preferences",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_5w2meonj",
            type: "Container",
            path: "CustomerOnboardingPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_o828lpkp",
                type: "Column",
                path: "CustomerOnboardingPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_5ujoi6we",
                    type: "ProgressBar",
                    path: "CustomerOnboardingPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_3ss4c3xg",
                    type: "ProgressBar",
                    path: "CustomerOnboardingPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_oh23xxlv",
                    type: "Text",
                    path: "CustomerOnboardingPage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_9hqv23tx",
                    type: "Column",
                    path: "CustomerOnboardingPage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_qz63gl80",
                        type: "Column",
                        path: "CustomerOnboardingPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_zlz176tk",
                            type: "Button",
                            path: "CustomerOnboardingPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_n0kgns9q",
                        type: "Button",
                        path: "CustomerOnboardingPage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_tqqn2ka0",
                    type: "Column",
                    path: "CustomerOnboardingPage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_ulw14tcp",
                        type: "Icon",
                        path: "CustomerOnboardingPage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_xp1ipetk",
                        type: "Text",
                        path: "CustomerOnboardingPage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_jpxh9mki",
                        type: "Button",
                        path: "CustomerOnboardingPage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_349hdca8",
                    type: "Column",
                    path: "CustomerOnboardingPage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_3wrduf1u",
                        type: "TextField",
                        path: "CustomerOnboardingPage.body[0].children[0].children[5].children[0]",
                        name: "WorkspaceField1",
                        text: "Your name",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_mfdl4b76",
                        type: "TextField",
                        path: "CustomerOnboardingPage.body[0].children[0].children[5].children[1]",
                        name: "WorkspaceField2",
                        text: "Phone (optional)",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_l98oa8k5",
                        type: "Column",
                        path: "CustomerOnboardingPage.body[0].children[0].children[5].children[2]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_rjvah3db",
                            type: "Button",
                            path: "CustomerOnboardingPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "Button",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_60djh5eg",
                            type: "Container",
                            path: "CustomerOnboardingPage.body[0].children[0].children[5].children[2].children[1]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "ListView_11opgcbn",
                                type: "ListView",
                                path: "CustomerOnboardingPage.body[0].children[0].children[5].children[2].children[1].children[0]",
                                name: "ListView",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_pj7qmdyi",
                                    type: "Button",
                                    path: "CustomerOnboardingPage.body[0].children[0].children[5].children[2].children[1].children[0].children[0]",
                                    name: "Button",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_qsuwl0ru",
                        type: "Column",
                        path: "CustomerOnboardingPage.body[0].children[0].children[5].children[3]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_kb9oi1u7",
                            type: "Button",
                            path: "CustomerOnboardingPage.body[0].children[0].children[5].children[3].children[0]",
                            name: "Button",
                            text: "Save profile",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_p91vyd95",
                        type: "Container",
                        path: "CustomerOnboardingPage.body[0].children[0].children[5].children[4]",
                        name: "WorkspaceMenuRow",
                        componentName: "WorkspaceMenuRow",
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

