// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final dealsMapPageHandle = ffai.ProjectPageHandle<DealsMapPageParams, DealsMapPageState>(
  name: "DealsMapPage",
  key: "Scaffold_bets0kvr",
  route: "deals-map",
  params: const DealsMapPageParams(),
  state: const DealsMapPageState(),
  widgets: DealsMapPageWidgets.tree,
);

final class DealsMapPageParams {
  const DealsMapPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "pvcmy2v4",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "blwnh54u",
        typeName: "String",
      );
}

final class DealsMapPageState {
  const DealsMapPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "ushydocq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "sj5mla6n",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "slmdrjxa",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "tyx03k9f",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "nooezc2i",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "2rxvnhva",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "4n6uaf7d",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "sjonrkl1",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "n1nrhmgr",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "4ifl4011",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "utstt7x6",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "19c0h9qo",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "l82w0nzr",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "ohlx9mw1",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "jk353trz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "uqqmwou7",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "wk6t66k1",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "xmilv8dx",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "ov16g7mm",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "3s6a3bjo",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "gg0oan2j",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "21o9ppaw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "9esrp1pa",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "kppuxg08",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "rf6fg5ex",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "zncjis35",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "wtqcjkfz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "p8e6m55q",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "1chwt1bs",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "7dcs19uj",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "acbz9oho",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "lcpdjnkt",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "a4iw6rjo",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "qtlh1iyb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "vujqnl91",
        typeName: "String",
      );
}

abstract final class DealsMapPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_bets0kvr",
      type: "Scaffold",
      path: "DealsMapPage",
      name: "DealsMapPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_7c9tkce5",
            type: "AppBar",
            path: "DealsMapPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_u0pujzxu",
                  type: "Text",
                  path: "DealsMapPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Activity map",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_fhxzsulf",
            type: "Container",
            path: "DealsMapPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_p6vi97np",
                type: "Column",
                path: "DealsMapPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_ybhfxvb3",
                    type: "ProgressBar",
                    path: "DealsMapPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_s9u9s0bk",
                    type: "ProgressBar",
                    path: "DealsMapPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_701uz3vi",
                    type: "Text",
                    path: "DealsMapPage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_rrhmzq5f",
                    type: "Column",
                    path: "DealsMapPage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_lq34xjjd",
                        type: "Column",
                        path: "DealsMapPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_13gh9hx1",
                            type: "Button",
                            path: "DealsMapPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_tr6w62hn",
                        type: "Button",
                        path: "DealsMapPage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_3wkh0q72",
                    type: "Column",
                    path: "DealsMapPage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_2dgo3cow",
                        type: "Icon",
                        path: "DealsMapPage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_043chye5",
                        type: "Text",
                        path: "DealsMapPage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_oc4x6oew",
                        type: "Button",
                        path: "DealsMapPage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_9m5bqxow",
                    type: "Column",
                    path: "DealsMapPage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_kiunoih7",
                        type: "Column",
                        path: "DealsMapPage.body[0].children[0].children[5].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_wjxugiv7",
                            type: "Button",
                            path: "DealsMapPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "Button",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_0915kmb3",
                            type: "Container",
                            path: "DealsMapPage.body[0].children[0].children[5].children[0].children[1]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "ListView_ol42x0e0",
                                type: "ListView",
                                path: "DealsMapPage.body[0].children[0].children[5].children[0].children[1].children[0]",
                                name: "ListView",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_a00us9fk",
                                    type: "Button",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[0].children[1].children[0].children[0]",
                                    name: "Button",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_r9fnznpb",
                        type: "Column",
                        path: "DealsMapPage.body[0].children[0].children[5].children[1]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_tcl3sylx",
                            type: "Button",
                            path: "DealsMapPage.body[0].children[0].children[5].children[1].children[0]",
                            name: "Button",
                            text: "Show activities",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_5qh0bhyt",
                        type: "Container",
                        path: "DealsMapPage.body[0].children[0].children[5].children[2]",
                        name: "Container",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "WebView_86fpcm4q",
                            type: "WebView",
                            path: "DealsMapPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "WebView",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_vg63qm2t",
                        type: "Container",
                        path: "DealsMapPage.body[0].children[0].children[5].children[3]",
                        name: "WorkspaceEmptyState",
                        componentName: "WorkspaceEmptyState",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_6mrfboff",
                        type: "ListView",
                        path: "DealsMapPage.body[0].children[0].children[5].children[4]",
                        name: "WorkspaceRecordList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_w6p93i2t",
                            type: "Container",
                            path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_e4ga5b4o",
                                type: "Column",
                                path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_dos4q5og",
                                    type: "Row",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[0]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_76afe2fo",
                                        type: "Text",
                                        path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[0].children[0]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_pi646kjn",
                                    type: "Text",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_crnjj0ka",
                                    type: "Text",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[2]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_1dfuzom1",
                                    type: "Text",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[3]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_ss6b7uj1",
                                    type: "Text",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[4]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_n56ua2ct",
                                    type: "Button",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[5]",
                                    name: "Button",
                                    text: "Show on map",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_yn2h1qok",
                                    type: "Button",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[6]",
                                    name: "Button",
                                    text: "Directions",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_p3b9n299",
                                    type: "Button",
                                    path: "DealsMapPage.body[0].children[0].children[5].children[4].children[0].children[0].children[7]",
                                    name: "Button",
                                    text: "View deal",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

