// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final dealsPageHandle = ffai.ProjectPageHandle<DealsPageParams, DealsPageState>(
  name: "DealsPage",
  key: "Scaffold_sau0xhtq",
  route: "deals",
  params: const DealsPageParams(),
  state: const DealsPageState(),
  widgets: DealsPageWidgets.tree,
);

final class DealsPageParams {
  const DealsPageParams();
}

final class DealsPageState {
  const DealsPageState();
  ffai.ProjectStateFieldHandle get category =>
      const ffai.ProjectStateFieldHandle(
        name: "category",
        key: "slwx9tqq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get city =>
      const ffai.ProjectStateFieldHandle(
        name: "city",
        key: "b434g6cp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get deals =>
      const ffai.ProjectStateFieldHandle(
        name: "deals",
        key: "4jop4pqr",
        typeName: "List<Document<listings>>",
      );
  ffai.ProjectStateFieldHandle get marketAdvanced =>
      const ffai.ProjectStateFieldHandle(
        name: "marketAdvanced",
        key: "dt76dm7j",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get marketBudget =>
      const ffai.ProjectStateFieldHandle(
        name: "marketBudget",
        key: "73i47zev",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCards =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCards",
        key: "z63ezgdc",
        typeName: "List<DataStruct<MobileAssistantCard>>",
      );
  ffai.ProjectStateFieldHandle get marketCategories =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCategories",
        key: "v2isy3ti",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get marketCategoryId =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCategoryId",
        key: "afuz186d",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCategoryLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCategoryLabel",
        key: "2o8mvdws",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCities =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCities",
        key: "ve5f4v6o",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get marketCityId =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCityId",
        key: "wy5abvbu",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCityLabel",
        key: "4pqmrm0c",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketEmpty =>
      const ffai.ProjectStateFieldHandle(
        name: "marketEmpty",
        key: "418mb91c",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get marketMenu =>
      const ffai.ProjectStateFieldHandle(
        name: "marketMenu",
        key: "42sr6v4w",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketOptionsView =>
      const ffai.ProjectStateFieldHandle(
        name: "marketOptionsView",
        key: "kph718xe",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketView =>
      const ffai.ProjectStateFieldHandle(
        name: "marketView",
        key: "blpdvr8a",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketWhen =>
      const ffai.ProjectStateFieldHandle(
        name: "marketWhen",
        key: "7ecpmave",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get smartQuery =>
      const ffai.ProjectStateFieldHandle(
        name: "smartQuery",
        key: "d7frxsik",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get smartSearchSummary =>
      const ffai.ProjectStateFieldHandle(
        name: "smartSearchSummary",
        key: "8m2somtu",
        typeName: "String",
      );
}

abstract final class DealsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_sau0xhtq",
      type: "Scaffold",
      path: "DealsPage",
      name: "DealsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_2y52loz8",
            type: "AppBar",
            path: "DealsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_24gwfb97",
                  type: "Text",
                  path: "DealsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Deals",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_037lyzt5",
            type: "Column",
            path: "DealsPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_kr6t7vk0",
                type: "Column",
                path: "DealsPage.body[0].children[0]",
                name: "MarketplaceBrowsePanel",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_hwmiwr1d",
                    type: "Text",
                    path: "DealsPage.body[0].children[0].children[0]",
                    name: "Text",
                    text: "Find an open spot",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_q0jtbp2d",
                    type: "Button",
                    path: "DealsPage.body[0].children[0].children[1]",
                    name: "BrowseCityPicker",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_qvdxzk0h",
                    type: "Column",
                    path: "DealsPage.body[0].children[0].children[2]",
                    name: "BrowsecityOptions",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_7x2wr6gi",
                        type: "Button",
                        path: "DealsPage.body[0].children[0].children[2].children[0]",
                        name: "Button",
                        text: "All cities",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_obx59qb0",
                        type: "ListView",
                        path: "DealsPage.body[0].children[0].children[2].children[1]",
                        name: "BrowsecityOptionList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_fus94mi5",
                            type: "Button",
                            path: "DealsPage.body[0].children[0].children[2].children[1].children[0]",
                            name: "Button",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_naogv68n",
                    type: "Row",
                    path: "DealsPage.body[0].children[0].children[3]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "DropDown_l6mpyeoy",
                        type: "DropDown",
                        path: "DealsPage.body[0].children[0].children[3].children[0]",
                        name: "BrowseWhenFilter",
                        triggers: const <String>[
                          "ON_FORM_WIDGET_SELECTED",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_96vkmbzj",
                        type: "Button",
                        path: "DealsPage.body[0].children[0].children[3].children[1]",
                        name: "BrowseMoreFilters",
                        text: "Filters",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_ao2glzhj",
                    type: "Button",
                    path: "DealsPage.body[0].children[0].children[4]",
                    name: "BrowseCategoryPicker",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_ofzida3m",
                    type: "Column",
                    path: "DealsPage.body[0].children[0].children[5]",
                    name: "BrowsecategoryOptions",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_rbdldy8m",
                        type: "Button",
                        path: "DealsPage.body[0].children[0].children[5].children[0]",
                        name: "Button",
                        text: "All categories",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_ni1xa7vp",
                        type: "ListView",
                        path: "DealsPage.body[0].children[0].children[5].children[1]",
                        name: "BrowsecategoryOptionList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_j3ql0pi9",
                            type: "Button",
                            path: "DealsPage.body[0].children[0].children[5].children[1].children[0]",
                            name: "Button",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "DropDown_0hw43pwr",
                    type: "DropDown",
                    path: "DealsPage.body[0].children[0].children[6]",
                    name: "BrowseBudgetFilter",
                    triggers: const <String>[
                      "ON_FORM_WIDGET_SELECTED",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_646owml1",
                    type: "Button",
                    path: "DealsPage.body[0].children[0].children[7]",
                    name: "Button",
                    text: "Retry city and category list",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_c1h1yod0",
                    type: "ProgressBar",
                    path: "DealsPage.body[0].children[0].children[8]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_r3m0d46h",
                    type: "Column",
                    path: "DealsPage.body[0].children[0].children[9]",
                    name: "BrowseLoadError",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_wnxk0cj8",
                        type: "Text",
                        path: "DealsPage.body[0].children[0].children[9].children[0]",
                        name: "Text",
                        text: "Deals could not load. Check your connection and try again.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_7w42y26z",
                        type: "Button",
                        path: "DealsPage.body[0].children[0].children[9].children[1]",
                        name: "Button",
                        text: "Retry deals",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_lqojeuf0",
                        type: "Button",
                        path: "DealsPage.body[0].children[0].children[9].children[2]",
                        name: "Button",
                        text: "Browse on website",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_pdjh3eve",
                    type: "Column",
                    path: "DealsPage.body[0].children[0].children[10]",
                    name: "BrowseEmptyState",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_0sti0rht",
                        type: "Text",
                        path: "DealsPage.body[0].children[0].children[10].children[0]",
                        name: "Text",
                        text: "No open deals match yet",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_9mp9vsyo",
                        type: "Text",
                        path: "DealsPage.body[0].children[0].children[10].children[1]",
                        name: "Text",
                        text: "Try another time or category, or join the city waitlist.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_8vh1s98z",
                        type: "Button",
                        path: "DealsPage.body[0].children[0].children[10].children[2]",
                        name: "Button",
                        text: "Join city waitlist",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_tlvzk89s",
                    type: "ListView",
                    path: "DealsPage.body[0].children[0].children[11]",
                    name: "MarketplaceDealList",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_hel5gxqw",
                        type: "Container",
                        path: "DealsPage.body[0].children[0].children[11].children[0]",
                        name: "MarketplaceDealCard",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_8imykn9y",
                            type: "Column",
                            path: "DealsPage.body[0].children[0].children[11].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Image_n9p7z24b",
                                type: "Image",
                                path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[0]",
                                name: "Image",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_a041tgzh",
                                type: "Container",
                                path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1]",
                                name: "Container",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_oc20z98e",
                                    type: "Column",
                                    path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_hllef3vm",
                                        type: "Text",
                                        path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_v8a9xp7n",
                                        type: "Text",
                                        path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_zlkrzslj",
                                        type: "Text",
                                        path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_wh8rjb78",
                                        type: "Text",
                                        path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0].children[3]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_woexttah",
                                        type: "Text",
                                        path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0].children[4]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_3we4zh8d",
                                        type: "Text",
                                        path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0].children[5]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Button_7sywvehx",
                                        type: "Button",
                                        path: "DealsPage.body[0].children[0].children[11].children[0].children[0].children[1].children[0].children[6]",
                                        name: "BrowseOpenDeal",
                                        text: "View Deal",
                                        triggers: const <String>[
                                          "ON_TAP",
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_ncbogsma",
                    type: "Button",
                    path: "DealsPage.body[0].children[0].children[12]",
                    name: "BrowseRefreshDeals",
                    text: "Refresh deals",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_rfaezrry",
                type: "Button",
                path: "DealsPage.body[0].children[1]",
                name: "MobileSmartSearchPanel",
                text: "Ask AI to find a deal",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

