// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final discoverPageHandle = ffai.ProjectPageHandle<DiscoverPageParams, DiscoverPageState>(
  name: "DiscoverPage",
  key: "Scaffold_zvhlzk7l",
  route: "",
  params: const DiscoverPageParams(),
  state: const DiscoverPageState(),
  widgets: DiscoverPageWidgets.tree,
);

final class DiscoverPageParams {
  const DiscoverPageParams();
}

final class DiscoverPageState {
  const DiscoverPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "53ygteoy",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get featuredDeals =>
      const ffai.ProjectStateFieldHandle(
        name: "featuredDeals",
        key: "d1g5qskd",
        typeName: "List<Document<listings>>",
      );
  ffai.ProjectStateFieldHandle get marketAdvanced =>
      const ffai.ProjectStateFieldHandle(
        name: "marketAdvanced",
        key: "np2fnqvi",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get marketBudget =>
      const ffai.ProjectStateFieldHandle(
        name: "marketBudget",
        key: "k8tbmqcw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCards =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCards",
        key: "y7yqlhtz",
        typeName: "List<DataStruct<MobileAssistantCard>>",
      );
  ffai.ProjectStateFieldHandle get marketCategories =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCategories",
        key: "90uz6aan",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get marketCategoryId =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCategoryId",
        key: "2p9ljbj5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCategoryLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCategoryLabel",
        key: "34ddo0vy",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCities =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCities",
        key: "jeaz0zhn",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get marketCityId =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCityId",
        key: "ohqd2s0h",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketCityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "marketCityLabel",
        key: "2oi85qkr",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketEmpty =>
      const ffai.ProjectStateFieldHandle(
        name: "marketEmpty",
        key: "5v43lye5",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get marketMenu =>
      const ffai.ProjectStateFieldHandle(
        name: "marketMenu",
        key: "46e13gfz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketOptionsView =>
      const ffai.ProjectStateFieldHandle(
        name: "marketOptionsView",
        key: "38xlz5lf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketView =>
      const ffai.ProjectStateFieldHandle(
        name: "marketView",
        key: "bdrlkxp4",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get marketWhen =>
      const ffai.ProjectStateFieldHandle(
        name: "marketWhen",
        key: "bvlt2tb1",
        typeName: "String",
      );
}

abstract final class DiscoverPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_zvhlzk7l",
      type: "Scaffold",
      path: "DiscoverPage",
      name: "DiscoverPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_shxqdeor",
            type: "AppBar",
            path: "DiscoverPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_xl2vexjn",
                  type: "Text",
                  path: "DiscoverPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "GoFunMotion",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_n23oclcb",
            type: "Column",
            path: "DiscoverPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_u3gjk2tb",
                type: "Column",
                path: "DiscoverPage.body[0].children[0]",
                name: "DealFirstDiscoveryHeader",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_8uxjjxtm",
                    type: "Text",
                    path: "DiscoverPage.body[0].children[0].children[0]",
                    name: "DealFirstDiscoveryTitle",
                    text: "Last-minute fun deals near you.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_c3vqulaq",
                    type: "Text",
                    path: "DiscoverPage.body[0].children[0].children[1]",
                    name: "DealFirstDiscoverySubtitle",
                    text: "Save on activities, date nights, and family fun with open spots today.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_i45wdvf7",
                    type: "Button",
                    path: "DiscoverPage.body[0].children[0].children[2]",
                    name: "HeroDealsButton",
                    text: "Tonight's Deals",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_3ilfhx9t",
                type: "Button",
                path: "DiscoverPage.body[0].children[1]",
                name: "DiscoverAssistantEntry",
                text: "AI Fun Finder",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_kwb0pbh7",
                type: "Column",
                path: "DiscoverPage.body[0].children[2]",
                name: "MarketplaceBrowsePanel",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_vdas34gv",
                    type: "Text",
                    path: "DiscoverPage.body[0].children[2].children[0]",
                    name: "Text",
                    text: "Find an open spot",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Row_r6ueyazg",
                    type: "Row",
                    path: "DiscoverPage.body[0].children[2].children[1]",
                    name: "Row",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_8qu2dq08",
                        type: "Button",
                        path: "DiscoverPage.body[0].children[2].children[1].children[0]",
                        name: "BrowseCityPicker",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "DropDown_33f214rx",
                        type: "DropDown",
                        path: "DiscoverPage.body[0].children[2].children[1].children[1]",
                        name: "BrowseWhenFilter",
                        triggers: const <String>[
                          "ON_FORM_WIDGET_SELECTED",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "IconButton_u5qmgaby",
                        type: "IconButton",
                        path: "DiscoverPage.body[0].children[2].children[1].children[2]",
                        name: "BrowseMoreFilters",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_86pvx7ac",
                    type: "Column",
                    path: "DiscoverPage.body[0].children[2].children[2]",
                    name: "BrowsecityOptions",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_phbkf8pg",
                        type: "Button",
                        path: "DiscoverPage.body[0].children[2].children[2].children[0]",
                        name: "Button",
                        text: "All cities",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_31td3pq3",
                        type: "ListView",
                        path: "DiscoverPage.body[0].children[2].children[2].children[1]",
                        name: "BrowsecityOptionList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_cn1c9njd",
                            type: "Button",
                            path: "DiscoverPage.body[0].children[2].children[2].children[1].children[0]",
                            name: "Button",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_ot21x3ku",
                    type: "Button",
                    path: "DiscoverPage.body[0].children[2].children[3]",
                    name: "BrowseCategoryPicker",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_yf4z0oce",
                    type: "Column",
                    path: "DiscoverPage.body[0].children[2].children[4]",
                    name: "BrowsecategoryOptions",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Button_fy0m88vz",
                        type: "Button",
                        path: "DiscoverPage.body[0].children[2].children[4].children[0]",
                        name: "Button",
                        text: "All categories",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_5d0kpkvs",
                        type: "ListView",
                        path: "DiscoverPage.body[0].children[2].children[4].children[1]",
                        name: "BrowsecategoryOptionList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_0e2nx8h5",
                            type: "Button",
                            path: "DiscoverPage.body[0].children[2].children[4].children[1].children[0]",
                            name: "Button",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "DropDown_drqyfxgg",
                    type: "DropDown",
                    path: "DiscoverPage.body[0].children[2].children[5]",
                    name: "BrowseBudgetFilter",
                    triggers: const <String>[
                      "ON_FORM_WIDGET_SELECTED",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_0vbqqvcb",
                    type: "Button",
                    path: "DiscoverPage.body[0].children[2].children[6]",
                    name: "Button",
                    text: "Retry city and category list",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_dwwql5nd",
                    type: "ProgressBar",
                    path: "DiscoverPage.body[0].children[2].children[7]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_n1r6a2zz",
                    type: "Column",
                    path: "DiscoverPage.body[0].children[2].children[8]",
                    name: "BrowseLoadError",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_s6uojtkh",
                        type: "Text",
                        path: "DiscoverPage.body[0].children[2].children[8].children[0]",
                        name: "Text",
                        text: "Deals could not load. Check your connection and try again.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_dtniowgd",
                        type: "Button",
                        path: "DiscoverPage.body[0].children[2].children[8].children[1]",
                        name: "Button",
                        text: "Retry deals",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_jh70pb3e",
                        type: "Button",
                        path: "DiscoverPage.body[0].children[2].children[8].children[2]",
                        name: "Button",
                        text: "Browse on website",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_81uvioql",
                    type: "Column",
                    path: "DiscoverPage.body[0].children[2].children[9]",
                    name: "BrowseEmptyState",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_2xeoftkl",
                        type: "Text",
                        path: "DiscoverPage.body[0].children[2].children[9].children[0]",
                        name: "Text",
                        text: "No open deals match yet",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_8a4faja4",
                        type: "Text",
                        path: "DiscoverPage.body[0].children[2].children[9].children[1]",
                        name: "Text",
                        text: "Try another time or category, or join the city waitlist.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_gk6hzjiv",
                        type: "Button",
                        path: "DiscoverPage.body[0].children[2].children[9].children[2]",
                        name: "Button",
                        text: "Join city waitlist",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListView_yzu3npy9",
                    type: "ListView",
                    path: "DiscoverPage.body[0].children[2].children[10]",
                    name: "MarketplaceDealList",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_nraqa6ha",
                        type: "Container",
                        path: "DiscoverPage.body[0].children[2].children[10].children[0]",
                        name: "MarketplaceDealCard",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_lxjaebuy",
                            type: "Column",
                            path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Image_hrdv79lm",
                                type: "Image",
                                path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[0]",
                                name: "Image",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_yskeu7e5",
                                type: "Container",
                                path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1]",
                                name: "Container",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_drx9ppjd",
                                    type: "Column",
                                    path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_5jhfioxm",
                                        type: "Text",
                                        path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_48clpzys",
                                        type: "Text",
                                        path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_6dflwxyg",
                                        type: "Text",
                                        path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_2ebppanf",
                                        type: "Text",
                                        path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0].children[3]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_w93uciok",
                                        type: "Text",
                                        path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0].children[4]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_m6o8k53m",
                                        type: "Text",
                                        path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0].children[5]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Button_9amvdkjs",
                                        type: "Button",
                                        path: "DiscoverPage.body[0].children[2].children[10].children[0].children[0].children[1].children[0].children[6]",
                                        name: "BrowseOpenDeal",
                                        text: "View Deal",
                                        triggers: const <String>[
                                          "ON_TAP",
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_qgylf415",
                    type: "Button",
                    path: "DiscoverPage.body[0].children[2].children[11]",
                    name: "BrowseRefreshDeals",
                    text: "Refresh deals",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_2bakvp3b",
                type: "Column",
                path: "DiscoverPage.body[0].children[3]",
                name: "NativeWorkspaceNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_b0kmrjkr",
                    type: "Container",
                    path: "DiscoverPage.body[0].children[3].children[0]",
                    name: "WorkspaceMenuRow",
                    componentName: "WorkspaceMenuRow",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_k0nlzr3s",
                    type: "Container",
                    path: "DiscoverPage.body[0].children[3].children[1]",
                    name: "WorkspaceMenuRow",
                    componentName: "WorkspaceMenuRow",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

