// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final exampleActivitiesPageHandle = ffai.ProjectPageHandle<ExampleActivitiesPageParams, ExampleActivitiesPageState>(
  name: "ExampleActivitiesPage",
  key: "Scaffold_6oysgmo3",
  route: "example-activities",
  params: const ExampleActivitiesPageParams(),
  state: const ExampleActivitiesPageState(),
  widgets: ExampleActivitiesPageWidgets.tree,
);

final class ExampleActivitiesPageParams {
  const ExampleActivitiesPageParams();
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "fwc7y5rf",
        typeName: "String",
      );
}

final class ExampleActivitiesPageState {
  const ExampleActivitiesPageState();
  ffai.ProjectStateFieldHandle get discoveryCards =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryCards",
        key: "udphww86",
        typeName: "List<DataStruct<DiscoveryOfferV1>>",
      );
  ffai.ProjectStateFieldHandle get discoveryCatalog =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryCatalog",
        key: "gjqw2w6o",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get discoveryCities =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryCities",
        key: "8v7sq9o5",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get discoveryCitiesOpen =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryCitiesOpen",
        key: "7klk0u58",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get discoveryCityId =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryCityId",
        key: "n680ijky",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get discoveryCityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryCityLabel",
        key: "706tdvp8",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get discoveryEmpty =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryEmpty",
        key: "xt26eeno",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get discoveryMapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryMapUrl",
        key: "gveirrg9",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get discoveryNotice =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryNotice",
        key: "xz3wg004",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get discoveryView =>
      const ffai.ProjectStateFieldHandle(
        name: "discoveryView",
        key: "2ssp4na4",
        typeName: "String",
      );
}

abstract final class ExampleActivitiesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_6oysgmo3",
      type: "Scaffold",
      path: "ExampleActivitiesPage",
      name: "ExampleActivitiesPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_o5bcr7pv",
            type: "AppBar",
            path: "ExampleActivitiesPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_4ztzsi8u",
                  type: "Text",
                  path: "ExampleActivitiesPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Explore examples",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_nx4po6s6",
            type: "Column",
            path: "ExampleActivitiesPage.body[0]",
            name: "DiscoveryScreenBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_w8t24h7r",
                type: "Column",
                path: "ExampleActivitiesPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Button_1ogrs71d",
                    type: "Button",
                    path: "ExampleActivitiesPage.body[0].children[0].children[0]",
                    name: "DiscoveryCityButton",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_km7dvsdt",
                    type: "Container",
                    path: "ExampleActivitiesPage.body[0].children[0].children[1]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_r0ac2tuu",
                        type: "Column",
                        path: "ExampleActivitiesPage.body[0].children[0].children[1].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_q4ab09mk",
                            type: "Button",
                            path: "ExampleActivitiesPage.body[0].children[0].children[1].children[0].children[0]",
                            name: "Button",
                            text: "All cities",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ListView_cvm9rkay",
                            type: "ListView",
                            path: "ExampleActivitiesPage.body[0].children[0].children[1].children[0].children[1]",
                            name: "DiscoveryCityOptions",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Button_sd18xu03",
                                type: "Button",
                                path: "ExampleActivitiesPage.body[0].children[0].children[1].children[0].children[1].children[0]",
                                name: "Button",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_o6w2ch1q",
                type: "Text",
                path: "ExampleActivitiesPage.body[0].children[1]",
                name: "Text",
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_l4wvpbrc",
                type: "Column",
                path: "ExampleActivitiesPage.body[0].children[2]",
                name: "DiscoveryFeedback",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_9ca158rr",
                    type: "Text",
                    path: "ExampleActivitiesPage.body[0].children[2].children[0]",
                    name: "Text",
                    text: "Loading offers...",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_gz3y7c6j",
                    type: "Column",
                    path: "ExampleActivitiesPage.body[0].children[2].children[1]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_xztmf9xp",
                        type: "Text",
                        path: "ExampleActivitiesPage.body[0].children[2].children[1].children[0]",
                        name: "Text",
                        text: "Offers could not load. Please try again.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_dqwne1oi",
                        type: "Button",
                        path: "ExampleActivitiesPage.body[0].children[2].children[1].children[1]",
                        name: "Button",
                        text: "Retry",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_h8173hwa",
                    type: "Column",
                    path: "ExampleActivitiesPage.body[0].children[2].children[2]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_x7ntalm8",
                        type: "Text",
                        path: "ExampleActivitiesPage.body[0].children[2].children[2].children[0]",
                        name: "Text",
                        text: "No open deals in this area yet",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_i1sjtuey",
                        type: "Text",
                        path: "ExampleActivitiesPage.body[0].children[2].children[2].children[1]",
                        name: "Text",
                        text: "Try another city, explore examples, or get notified when deals arrive.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_2b3n3fjs",
                        type: "Button",
                        path: "ExampleActivitiesPage.body[0].children[2].children[2].children[2]",
                        name: "Button",
                        text: "Explore examples",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_slcg13fe",
                        type: "Button",
                        path: "ExampleActivitiesPage.body[0].children[2].children[2].children[3]",
                        name: "Button",
                        text: "Join city waitlist",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_1qgpzeen",
                type: "ListView",
                path: "ExampleActivitiesPage.body[0].children[3]",
                name: "DiscoveryOfferList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_co5q6g1g",
                    type: "Container",
                    path: "ExampleActivitiesPage.body[0].children[3].children[0]",
                    name: "DiscoveryOfferCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_dra8qcja",
                        type: "Column",
                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Image_4z9rmat7",
                            type: "Image",
                            path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[0]",
                            name: "Image",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_ytypu1p4",
                            type: "Container",
                            path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_4eia0obm",
                                type: "Column",
                                path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_x4xhjuci",
                                    type: "Row",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[0]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_eycbipib",
                                        type: "Icon",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_8qu6dkdl",
                                        type: "Text",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[0].children[1]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_zb99cok0",
                                        type: "Text",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[0].children[2]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_wg2gsrky",
                                    type: "Text",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[1]",
                                    name: "Text",
                                    text: "EXAMPLE / NOT BOOKABLE",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_w002fwt5",
                                    type: "Text",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[2]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_7hm5kev4",
                                    type: "Text",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[3]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_uwl9jyzf",
                                    type: "Row",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[4]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_payl4wxx",
                                        type: "Text",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[4].children[0]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_t9wejn8n",
                                        type: "Text",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[4].children[1]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_8pq9txro",
                                    type: "Row",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[5]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_9bjpm1lr",
                                        type: "Icon",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[5].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_msy0tg54",
                                        type: "Text",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[5].children[1]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_ezc0a1eo",
                                    type: "Row",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[6]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_4sehnm0w",
                                        type: "Icon",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[6].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_l5v57w4p",
                                        type: "Text",
                                        path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[6].children[1]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_hu7oiswk",
                                    type: "Button",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[7]",
                                    name: "OpenExampleActivity",
                                    text: "View example",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_he1ymk8x",
                                    type: "Button",
                                    path: "ExampleActivitiesPage.body[0].children[3].children[0].children[0].children[1].children[0].children[8]",
                                    name: "OpenLiveMapDeal",
                                    text: "View deal",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_2elnrk49",
                type: "Button",
                path: "ExampleActivitiesPage.body[0].children[4]",
                name: "Button",
                text: "Refresh offers",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_msr5yk3u",
                type: "Container",
                path: "ExampleActivitiesPage.body[0].children[5]",
                name: "Spacer",
              ),
            ],
          ),
        ],
      },
    ),
  );
}

