// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final listingReviewsPageHandle = ffai.ProjectPageHandle<ListingReviewsPageParams, ListingReviewsPageState>(
  name: "ListingReviewsPage",
  key: "Scaffold_jobks8f6",
  route: "listing-reviews",
  params: const ListingReviewsPageParams(),
  state: const ListingReviewsPageState(),
  widgets: ListingReviewsPageWidgets.tree,
);

final class ListingReviewsPageParams {
  const ListingReviewsPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "c1m2fumu",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "3rkcvo10",
        typeName: "String",
      );
}

final class ListingReviewsPageState {
  const ListingReviewsPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "tnch77bb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "h6q4dgd3",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "y9r1w3u6",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "stgq1cl1",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "l2rbmgmf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "iy30cd57",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "460928l5",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "g1sol3rk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "1a0ig7kp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "leaomvwa",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "s06ezt4g",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "gmacy7i7",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "ooz0py3r",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "l2ilszrr",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "eexr5on7",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "a2pzv7uo",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "jfgxei1t",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "tfg20b49",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "wlr4amap",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "pjls8seh",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "73pu50py",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "a31tga7e",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "2elmink5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "r5et7nct",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "njqqdya6",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "uucehfu0",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "f1o88kgd",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "y06eb1ja",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "fm2jjggv",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "6uvdnkgn",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "244bj4os",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "jiev1dov",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "xs6vauxp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "0onwxsep",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "qd344fo3",
        typeName: "String",
      );
}

abstract final class ListingReviewsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_jobks8f6",
      type: "Scaffold",
      path: "ListingReviewsPage",
      name: "ListingReviewsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_abrls3h5",
            type: "AppBar",
            path: "ListingReviewsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_h31nrwna",
                  type: "Text",
                  path: "ListingReviewsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Activity reviews",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_ud9ld2ko",
            type: "Container",
            path: "ListingReviewsPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_yjna0z8h",
                type: "Column",
                path: "ListingReviewsPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_smt1b09s",
                    type: "ProgressBar",
                    path: "ListingReviewsPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_007bhs5x",
                    type: "ProgressBar",
                    path: "ListingReviewsPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_8bav1cd6",
                    type: "Text",
                    path: "ListingReviewsPage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_w9dc1i9g",
                    type: "Column",
                    path: "ListingReviewsPage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_4rp2x3gx",
                        type: "Column",
                        path: "ListingReviewsPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_sx75dfv4",
                            type: "Button",
                            path: "ListingReviewsPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_d13ypbj0",
                        type: "Button",
                        path: "ListingReviewsPage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_3p1aep2s",
                    type: "Column",
                    path: "ListingReviewsPage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_p27u9gse",
                        type: "Icon",
                        path: "ListingReviewsPage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_88z9g5k4",
                        type: "Text",
                        path: "ListingReviewsPage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_qql6p5l0",
                        type: "Button",
                        path: "ListingReviewsPage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_i0o0ubao",
                    type: "Column",
                    path: "ListingReviewsPage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_hfsp6udn",
                        type: "Row",
                        path: "ListingReviewsPage.body[0].children[0].children[5].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_3kwtojiw",
                            type: "Text",
                            path: "ListingReviewsPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "Text",
                            text: "Records",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_d54hsq80",
                            type: "IconButton",
                            path: "ListingReviewsPage.body[0].children[0].children[5].children[0].children[1]",
                            name: "RefreshWorkspaceList",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_zsizys7q",
                        type: "Container",
                        path: "ListingReviewsPage.body[0].children[0].children[5].children[1]",
                        name: "WorkspaceEmptyState",
                        componentName: "WorkspaceEmptyState",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_l9xmoi14",
                        type: "ListView",
                        path: "ListingReviewsPage.body[0].children[0].children[5].children[2]",
                        name: "WorkspaceRecordList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_xnmvwfjs",
                            type: "Container",
                            path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_06r00hh8",
                                type: "Column",
                                path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_xl3yhbxe",
                                    type: "Row",
                                    path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[0]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_pv1ynya8",
                                        type: "Text",
                                        path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[0].children[0]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_x4ul28ah",
                                    type: "Text",
                                    path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_b3pwvtwy",
                                    type: "Text",
                                    path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[2]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_g6c791k4",
                                    type: "Text",
                                    path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[3]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_8lgi5hm8",
                                    type: "Text",
                                    path: "ListingReviewsPage.body[0].children[0].children[5].children[2].children[0].children[0].children[4]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_0iyb4i34",
                        type: "Row",
                        path: "ListingReviewsPage.body[0].children[0].children[5].children[3]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_1js9eiwu",
                            type: "Button",
                            path: "ListingReviewsPage.body[0].children[0].children[5].children[3].children[0]",
                            name: "Button",
                            text: "First page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_9upab2n0",
                            type: "Button",
                            path: "ListingReviewsPage.body[0].children[0].children[5].children[3].children[1]",
                            name: "Button",
                            text: "Next page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

