// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final partnerAnalyticsPageHandle = ffai.ProjectPageHandle<PartnerAnalyticsPageParams, PartnerAnalyticsPageState>(
  name: "PartnerAnalyticsPage",
  key: "Scaffold_rr3r71vr",
  route: "partner-analytics",
  params: const PartnerAnalyticsPageParams(),
  state: const PartnerAnalyticsPageState(),
  widgets: PartnerAnalyticsPageWidgets.tree,
);

final class PartnerAnalyticsPageParams {
  const PartnerAnalyticsPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "9ikj9oiz",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "uzyc9fm1",
        typeName: "String",
      );
}

final class PartnerAnalyticsPageState {
  const PartnerAnalyticsPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "vphyeuku",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "qim9vuwo",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "bm097b80",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "xv5cqcil",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "dzwndp3v",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "rdwsahca",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "wohsrykn",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "6cdsyjwp",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "og0050qw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "dck49cvp",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "8p2k89rf",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "npkgcn36",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "edqo2m7f",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "h5gcsnhu",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "xefw0ti4",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "123akttl",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "xi7bzfaz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "9j91fpsp",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "tqy2ukdz",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "0jcdu376",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "3sj65xr5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "8sq7xohb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "xuzaa9pw",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "ibbd8kih",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "6czvkmtq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "x9udhnlh",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "shu1y0ea",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "8roef5ya",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "94c6pia5",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "s7l9nhk9",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "tx13tyq0",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "0mowxk3i",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "nvsb0i4x",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "i7rct8y1",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "zqxt2qj5",
        typeName: "String",
      );
}

abstract final class PartnerAnalyticsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_rr3r71vr",
      type: "Scaffold",
      path: "PartnerAnalyticsPage",
      name: "PartnerAnalyticsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_kr1bkn5j",
            type: "AppBar",
            path: "PartnerAnalyticsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_ktd8cga3",
                  type: "Text",
                  path: "PartnerAnalyticsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Business analytics",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_xkjk0yei",
            type: "Container",
            path: "PartnerAnalyticsPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_bh5by07x",
                type: "Column",
                path: "PartnerAnalyticsPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_t99frjvn",
                    type: "ProgressBar",
                    path: "PartnerAnalyticsPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_34f7ptwb",
                    type: "ProgressBar",
                    path: "PartnerAnalyticsPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_1hhiyiuo",
                    type: "Text",
                    path: "PartnerAnalyticsPage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_gsc4q50z",
                    type: "Column",
                    path: "PartnerAnalyticsPage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_gvspyook",
                        type: "Column",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_01q9t4yl",
                            type: "Button",
                            path: "PartnerAnalyticsPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_7irppf5o",
                        type: "Button",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_b700t3ej",
                    type: "Column",
                    path: "PartnerAnalyticsPage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_8jpccoga",
                        type: "Icon",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_1wev5wnd",
                        type: "Text",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_8vqiwohu",
                        type: "Button",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_53hkozy9",
                    type: "Column",
                    path: "PartnerAnalyticsPage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_de6wqf7j",
                        type: "Text",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_x3xn9l6q",
                        type: "Container",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[1]",
                        name: "WorkspaceMenuRow",
                        componentName: "WorkspaceMenuRow",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_xlrgas4o",
                        type: "Row",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[2]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_3olh78an",
                            type: "Text",
                            path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[2].children[0]",
                            name: "Text",
                            text: "Records",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_7zjq2txj",
                            type: "IconButton",
                            path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[2].children[1]",
                            name: "RefreshWorkspaceList",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ob3dp1ff",
                        type: "Container",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[3]",
                        name: "WorkspaceEmptyState",
                        componentName: "WorkspaceEmptyState",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_1cahq4qc",
                        type: "ListView",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4]",
                        name: "WorkspaceRecordList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_n40ids3d",
                            type: "Container",
                            path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_kfl5v4om",
                                type: "Column",
                                path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_ewe1dg58",
                                    type: "Row",
                                    path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0].children[0].children[0]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_lvs9kkz3",
                                        type: "Text",
                                        path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0].children[0].children[0].children[0]",
                                        name: "Text",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_cs0u3me7",
                                    type: "Text",
                                    path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_7ew82rvl",
                                    type: "Text",
                                    path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0].children[0].children[2]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_a8zqgce9",
                                    type: "Text",
                                    path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0].children[0].children[3]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_izuxucj2",
                                    type: "Text",
                                    path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[4].children[0].children[0].children[4]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_r4eni2wg",
                        type: "Row",
                        path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[5]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_8v6wnk6e",
                            type: "Button",
                            path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[5].children[0]",
                            name: "Button",
                            text: "First page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_e5j2jdlg",
                            type: "Button",
                            path: "PartnerAnalyticsPage.body[0].children[0].children[5].children[5].children[1]",
                            name: "Button",
                            text: "Next page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

