// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final partnerSubscriptionPageHandle = ffai.ProjectPageHandle<PartnerSubscriptionPageParams, PartnerSubscriptionPageState>(
  name: "PartnerSubscriptionPage",
  key: "Scaffold_m2d9xtd3",
  route: "partner-subscription",
  params: const PartnerSubscriptionPageParams(),
  state: const PartnerSubscriptionPageState(),
  widgets: PartnerSubscriptionPageWidgets.tree,
);

final class PartnerSubscriptionPageParams {
  const PartnerSubscriptionPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "bwo1cp0x",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "qmlj7hvb",
        typeName: "String",
      );
}

final class PartnerSubscriptionPageState {
  const PartnerSubscriptionPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "warj0b3u",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "rmy5is8t",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "rvkf4d1d",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "x8ykdc2g",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "hlrxuhcc",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "zxohoo4f",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "vt1fj9cs",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "92dou9tj",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "bs3sbxit",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "zt8i8m8p",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "iyebqq7w",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "rlexeu2r",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "1jp41jqb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "1ynaskhz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "gjvbzmnh",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "9cezf8rt",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "xxobvtxc",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "ro7bi04u",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "3l8tc7lo",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "2eff3dov",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "p5jart0j",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "9xundyit",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "ifhu4tpr",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "m2pdnncm",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "mc3wtxe6",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "ze7yfx4s",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "shdi31xd",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "yo73w706",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "agq3qz4y",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "9pb0j6xq",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "8uo0s7yo",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "tthgdguu",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get storeBusy =>
      const ffai.ProjectStateFieldHandle(
        name: "storeBusy",
        key: "bdvqmb1q",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get storeReady =>
      const ffai.ProjectStateFieldHandle(
        name: "storeReady",
        key: "0wtepsrv",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get storeState =>
      const ffai.ProjectStateFieldHandle(
        name: "storeState",
        key: "paztttid",
        typeName: "DataStruct<NativeStoreState>",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "wa7jr71j",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "xjjuveie",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "5hr8kwz1",
        typeName: "String",
      );
}

abstract final class PartnerSubscriptionPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_m2d9xtd3",
      type: "Scaffold",
      path: "PartnerSubscriptionPage",
      name: "PartnerSubscriptionPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_jbvmaax5",
            type: "AppBar",
            path: "PartnerSubscriptionPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_4znn0ars",
                  type: "Text",
                  path: "PartnerSubscriptionPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Your subscription",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_msde403e",
            type: "Container",
            path: "PartnerSubscriptionPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_s1yda9c8",
                type: "Column",
                path: "PartnerSubscriptionPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_7t1rcngj",
                    type: "Text",
                    path: "PartnerSubscriptionPage.body[0].children[0].children[0]",
                    name: "NativeSubscriptionInitialLoading",
                    text: "Checking your subscription...",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_elianye7",
                    type: "Column",
                    path: "PartnerSubscriptionPage.body[0].children[0].children[1]",
                    name: "NativeSubscriptionContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_fobawvfj",
                        type: "Text",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[0]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_6s2zwlmj",
                        type: "Text",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[1]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_yvrkwpwc",
                        type: "Text",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[2]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_w79c1umy",
                        type: "Text",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[3]",
                        name: "StoreLoadingStatus",
                        text: "Checking your subscription...",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_e8ub8r2g",
                        type: "Text",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[4]",
                        name: "StoreResultMessage",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_0owxk1js",
                        type: "Container",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[5]",
                        name: "GrowthStorePlan",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_2dbdrsrn",
                            type: "Column",
                            path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[5].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_dnif208f",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[5].children[0].children[0]",
                                name: "Text",
                                text: "Growth",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_bckuchdj",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[5].children[0].children[1]",
                                name: "Text",
                                text: "10 active deals, analytics and featured eligibility.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_0aa76ike",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[5].children[0].children[2]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_odd8xo0g",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[5].children[0].children[3]",
                                name: "Text",
                                text: "per month",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_i2c0nrlf",
                                type: "Button",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[5].children[0].children[4]",
                                name: "GrowthStorePurchaseButton",
                                text: "Continue with Growth",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_7zhtpryx",
                        type: "Container",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[6]",
                        name: "ProStorePlan",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_duw59krz",
                            type: "Column",
                            path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[6].children[0]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_6m1zmkkh",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[6].children[0].children[0]",
                                name: "Text",
                                text: "Pro",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_519md7bf",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[6].children[0].children[1]",
                                name: "Text",
                                text: "Unlimited active deals, advanced analytics and team roster.",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_82y96ng7",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[6].children[0].children[2]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_sfvvxwkv",
                                type: "Text",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[6].children[0].children[3]",
                                name: "Text",
                                text: "per month",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Button_6sx5k4ak",
                                type: "Button",
                                path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[6].children[0].children[4]",
                                name: "ProStorePurchaseButton",
                                text: "Continue with Pro",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_4e7p3kh3",
                        type: "Button",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[7]",
                        name: "ManageNativeSubscriptionButton",
                        text: "Manage subscription",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_kzc937kk",
                        type: "Button",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[8]",
                        name: "RestoreNativePurchasesButton",
                        text: "Restore purchases",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_gxl8miuo",
                        type: "Button",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[9]",
                        name: "RefreshNativeSubscriptionButton",
                        text: "Refresh status",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_wtz649mx",
                        type: "Text",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[10]",
                        name: "Text",
                        text: "Monthly subscription. Payment is charged to your store account after confirmation. It renews automatically unless cancelled in your store account settings. Cancellation keeps access until the paid period ends.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_n1wada44",
                        type: "Text",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[11]",
                        name: "Text",
                        text: "One subscription covers one approved business. Bookings remain requests, not purchases.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_wfa0p9ff",
                        type: "Button",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[12]",
                        name: "Button",
                        text: "Terms of Use",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_1uw65pbf",
                        type: "Button",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[13]",
                        name: "Button",
                        text: "Privacy Policy",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_1u19fokk",
                        type: "Button",
                        path: "PartnerSubscriptionPage.body[0].children[0].children[1].children[14]",
                        name: "Button",
                        text: "Billing support",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

