// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final partnerListingsPageHandle = ffai.ProjectPageHandle<PartnerListingsPageParams, PartnerListingsPageState>(
  name: "PartnerListingsPage",
  key: "Scaffold_im6ftuoq",
  route: "partner-listings",
  params: const PartnerListingsPageParams(),
  state: const PartnerListingsPageState(),
  widgets: PartnerListingsPageWidgets.tree,
);

final class PartnerListingsPageParams {
  const PartnerListingsPageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "fkcvncaf",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "brexg66p",
        typeName: "String",
      );
}

final class PartnerListingsPageState {
  const PartnerListingsPageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "g3boziju",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "iovqv9gu",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "h5cezp4c",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "cd8zcgwu",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "cf99hz2c",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "qcrnz5gz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "v7aae490",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "ez9emjfz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "ijx0uclz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "t1srrfb3",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "43rxkepk",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "cjr29r4h",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "yo6797fd",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "ft9sp48g",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "4vxktoh3",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "aqzztzyz",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "dab364od",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "6gdhr5qt",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "uwp8e48j",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "nfvv3hul",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "ib8omvuk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "psqelr78",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "3mtswmih",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "63bznl8n",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "eoi89ar6",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "ds0nrxdj",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "5kbe7wn9",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "eznwnsky",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "xkbdx1fw",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "7e90756f",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "33lyjetm",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "7yq91eew",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "e1msiw7c",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "yj0o402m",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "nzk09jf3",
        typeName: "String",
      );
}

abstract final class PartnerListingsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_im6ftuoq",
      type: "Scaffold",
      path: "PartnerListingsPage",
      name: "PartnerListingsPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_9e7xqp5b",
            type: "AppBar",
            path: "PartnerListingsPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_l87v4zod",
                  type: "Text",
                  path: "PartnerListingsPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Your deals",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_xeh4k612",
            type: "Container",
            path: "PartnerListingsPage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_5a9z7yvk",
                type: "Column",
                path: "PartnerListingsPage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_gtriacdf",
                    type: "ProgressBar",
                    path: "PartnerListingsPage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_mfxam9dy",
                    type: "ProgressBar",
                    path: "PartnerListingsPage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_gmx8cpxq",
                    type: "Text",
                    path: "PartnerListingsPage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_qmn0k96z",
                    type: "Column",
                    path: "PartnerListingsPage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_uf4p17kv",
                        type: "Column",
                        path: "PartnerListingsPage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_5quo9rrv",
                            type: "Button",
                            path: "PartnerListingsPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_nby92l0e",
                        type: "Button",
                        path: "PartnerListingsPage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_jtjwsn57",
                    type: "Column",
                    path: "PartnerListingsPage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_p1owzo9d",
                        type: "Icon",
                        path: "PartnerListingsPage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_v9vgxdi9",
                        type: "Text",
                        path: "PartnerListingsPage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_gnn8dnyj",
                        type: "Button",
                        path: "PartnerListingsPage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_xt8wb18t",
                    type: "Column",
                    path: "PartnerListingsPage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_s20ne9b6",
                        type: "Column",
                        path: "PartnerListingsPage.body[0].children[0].children[5].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_cye9c6cf",
                            type: "Button",
                            path: "PartnerListingsPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "Button",
                            text: "Create last-minute deal",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_0q9bvro2",
                        type: "Row",
                        path: "PartnerListingsPage.body[0].children[0].children[5].children[1]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_0vnt29sl",
                            type: "Text",
                            path: "PartnerListingsPage.body[0].children[0].children[5].children[1].children[0]",
                            name: "Text",
                            text: "Records",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "IconButton_724wh1to",
                            type: "IconButton",
                            path: "PartnerListingsPage.body[0].children[0].children[5].children[1].children[1]",
                            name: "RefreshWorkspaceList",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_3nf0t5es",
                        type: "Container",
                        path: "PartnerListingsPage.body[0].children[0].children[5].children[2]",
                        name: "WorkspaceEmptyState",
                        componentName: "WorkspaceEmptyState",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_v5av8x5s",
                        type: "ListView",
                        path: "PartnerListingsPage.body[0].children[0].children[5].children[3]",
                        name: "WorkspaceRecordList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_1nbhvxmq",
                            type: "Container",
                            path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_deh8wqqf",
                                type: "Column",
                                path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_ziepjggl",
                                    type: "Row",
                                    path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0].children[0].children[0]",
                                    name: "Row",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_gp11hkm2",
                                        type: "Text",
                                        path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0].children[0].children[0].children[0]",
                                        name: "Text",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kwf9c8mt",
                                        type: "Icon",
                                        path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_mrlly2c4",
                                    type: "Text",
                                    path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0].children[0].children[1]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_vo5hn6wo",
                                    type: "Text",
                                    path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0].children[0].children[2]",
                                    name: "Text",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_4i9v5l3s",
                                    type: "Text",
                                    path: "PartnerListingsPage.body[0].children[0].children[5].children[3].children[0].children[0].children[3]",
                                    name: "Text",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Row_ng0tr7eo",
                        type: "Row",
                        path: "PartnerListingsPage.body[0].children[0].children[5].children[4]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_7di5wxkt",
                            type: "Button",
                            path: "PartnerListingsPage.body[0].children[0].children[5].children[4].children[0]",
                            name: "Button",
                            text: "First page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Button_lkgh568g",
                            type: "Button",
                            path: "PartnerListingsPage.body[0].children[0].children[5].children[4].children[1]",
                            name: "Button",
                            text: "Next page",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

