// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final partnerBusinessProfilePageHandle = ffai.ProjectPageHandle<PartnerBusinessProfilePageParams, PartnerBusinessProfilePageState>(
  name: "PartnerBusinessProfilePage",
  key: "Scaffold_7lvngilj",
  route: "partner-business-profile",
  params: const PartnerBusinessProfilePageParams(),
  state: const PartnerBusinessProfilePageState(),
  widgets: PartnerBusinessProfilePageWidgets.tree,
);

final class PartnerBusinessProfilePageParams {
  const PartnerBusinessProfilePageParams();
  ffai.ProjectParamHandle get businessId =>
      const ffai.ProjectParamHandle(
        name: "businessId",
        key: "cu60ush1",
        typeName: "String",
      );
  ffai.ProjectParamHandle get id =>
      const ffai.ProjectParamHandle(
        name: "id",
        key: "evaa89xu",
        typeName: "String",
      );
}

final class PartnerBusinessProfilePageState {
  const PartnerBusinessProfilePageState();
  ffai.ProjectStateFieldHandle get businessId =>
      const ffai.ProjectStateFieldHandle(
        name: "businessId",
        key: "e7y17irf",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get busy =>
      const ffai.ProjectStateFieldHandle(
        name: "busy",
        key: "oen6ke1w",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get canEdit =>
      const ffai.ProjectStateFieldHandle(
        name: "canEdit",
        key: "bc7awpq9",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cities =>
      const ffai.ProjectStateFieldHandle(
        name: "cities",
        key: "6xmx545j",
        typeName: "List<DataStruct<MobileAssistantCity>>",
      );
  ffai.ProjectStateFieldHandle get cityId =>
      const ffai.ProjectStateFieldHandle(
        name: "cityId",
        key: "x385u8s1",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get cityLabel =>
      const ffai.ProjectStateFieldHandle(
        name: "cityLabel",
        key: "n41jb60e",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get confirmed =>
      const ffai.ProjectStateFieldHandle(
        name: "confirmed",
        key: "o1wpe36w",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get cursor =>
      const ffai.ProjectStateFieldHandle(
        name: "cursor",
        key: "bke51na4",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get detail =>
      const ffai.ProjectStateFieldHandle(
        name: "detail",
        key: "6undgq7q",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get empty =>
      const ffai.ProjectStateFieldHandle(
        name: "empty",
        key: "haty24ym",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get endMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "endMillis",
        key: "xdjr1o2h",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get field1 =>
      const ffai.ProjectStateFieldHandle(
        name: "field1",
        key: "9jql3slt",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field2 =>
      const ffai.ProjectStateFieldHandle(
        name: "field2",
        key: "4oo2vqne",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field3 =>
      const ffai.ProjectStateFieldHandle(
        name: "field3",
        key: "5e6pv8hc",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field4 =>
      const ffai.ProjectStateFieldHandle(
        name: "field4",
        key: "h61y3w0m",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field5 =>
      const ffai.ProjectStateFieldHandle(
        name: "field5",
        key: "pz7dy7s2",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get field6 =>
      const ffai.ProjectStateFieldHandle(
        name: "field6",
        key: "xkblc08x",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get flag =>
      const ffai.ProjectStateFieldHandle(
        name: "flag",
        key: "kiwobzhh",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get hasMore =>
      const ffai.ProjectStateFieldHandle(
        name: "hasMore",
        key: "yr0whusc",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get isAdmin =>
      const ffai.ProjectStateFieldHandle(
        name: "isAdmin",
        key: "w7ix61hw",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get mapUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "mapUrl",
        key: "qdvdma2c",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get message =>
      const ffai.ProjectStateFieldHandle(
        name: "message",
        key: "l4hqjvl2",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextCursor =>
      const ffai.ProjectStateFieldHandle(
        name: "nextCursor",
        key: "pg14295q",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get nextStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "nextStatus",
        key: "vhnwxn3d",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerEmail =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerEmail",
        key: "iplbi4ox",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get ownerUid =>
      const ffai.ProjectStateFieldHandle(
        name: "ownerUid",
        key: "yro54hmi",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get recordId =>
      const ffai.ProjectStateFieldHandle(
        name: "recordId",
        key: "2xftbwfu",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get role =>
      const ffai.ProjectStateFieldHandle(
        name: "role",
        key: "oapvp7pb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rows =>
      const ffai.ProjectStateFieldHandle(
        name: "rows",
        key: "qkzprpfq",
        typeName: "List<DataStruct<MobileWorkspaceRow>>",
      );
  ffai.ProjectStateFieldHandle get showCities =>
      const ffai.ProjectStateFieldHandle(
        name: "showCities",
        key: "ajmu7v27",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get startMillis =>
      const ffai.ProjectStateFieldHandle(
        name: "startMillis",
        key: "6d49k0ta",
        typeName: "Integer",
      );
  ffai.ProjectStateFieldHandle get status =>
      const ffai.ProjectStateFieldHandle(
        name: "status",
        key: "g7k9c8nb",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get summary =>
      const ffai.ProjectStateFieldHandle(
        name: "summary",
        key: "eqwd5ib8",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get title =>
      const ffai.ProjectStateFieldHandle(
        name: "title",
        key: "z5xnamx5",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get view =>
      const ffai.ProjectStateFieldHandle(
        name: "view",
        key: "xxcl7etk",
        typeName: "String",
      );
}

abstract final class PartnerBusinessProfilePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_7lvngilj",
      type: "Scaffold",
      path: "PartnerBusinessProfilePage",
      name: "PartnerBusinessProfilePage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_ad8dlwy3",
            type: "AppBar",
            path: "PartnerBusinessProfilePage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_5wm5amf8",
                  type: "Text",
                  path: "PartnerBusinessProfilePage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Business profile",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_zc3hafnk",
            type: "Container",
            path: "PartnerBusinessProfilePage.body[0]",
            name: "Container",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_r3cv1hot",
                type: "Column",
                path: "PartnerBusinessProfilePage.body[0].children[0]",
                name: "WorkspaceScreenBody",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_slhzsf2a",
                    type: "ProgressBar",
                    path: "PartnerBusinessProfilePage.body[0].children[0].children[0]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ProgressBar_uxac43lb",
                    type: "ProgressBar",
                    path: "PartnerBusinessProfilePage.body[0].children[0].children[1]",
                    name: "ProgressBar",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_qbh79yws",
                    type: "Text",
                    path: "PartnerBusinessProfilePage.body[0].children[0].children[2]",
                    name: "Text",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_wsx350bs",
                    type: "Column",
                    path: "PartnerBusinessProfilePage.body[0].children[0].children[3]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_e3f2t2re",
                        type: "Column",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[3].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_y4r3stbc",
                            type: "Button",
                            path: "PartnerBusinessProfilePage.body[0].children[0].children[3].children[0].children[0]",
                            name: "Button",
                            text: "Retry",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_dlh37t5o",
                        type: "Button",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[3].children[1]",
                        name: "Button",
                        text: "Sign in again",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_ohky2fw7",
                    type: "Column",
                    path: "PartnerBusinessProfilePage.body[0].children[0].children[4]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_ndrzf9c5",
                        type: "Icon",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[4].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_4ydfszm7",
                        type: "Text",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[4].children[1]",
                        name: "Text",
                        text: "Administrator access required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_xcav00zl",
                        type: "Button",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[4].children[2]",
                        name: "Button",
                        text: "Back to account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_v1dqb3qm",
                    type: "Column",
                    path: "PartnerBusinessProfilePage.body[0].children[0].children[5]",
                    name: "WorkspaceReadyContent",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_mnx4h7ty",
                        type: "TextField",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[0]",
                        name: "WorkspaceField1",
                        text: "Business name",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_q9t5208c",
                        type: "TextField",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[1]",
                        name: "WorkspaceField2",
                        text: "Phone",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_86e58zcf",
                        type: "TextField",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[2]",
                        name: "WorkspaceField3",
                        text: "Website (https://)",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_7g4h641g",
                        type: "TextField",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[3]",
                        name: "WorkspaceField4",
                        text: "About your business",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_vscklxxb",
                        type: "TextField",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[4]",
                        name: "WorkspaceField5",
                        text: "Street address",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_qwcumeft",
                        type: "TextField",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[5]",
                        name: "WorkspaceField6",
                        text: "Postal code",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_kjj19nl6",
                        type: "Text",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[6]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_zk2ljlc0",
                        type: "Column",
                        path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[7]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Button_fsmsgn83",
                            type: "Button",
                            path: "PartnerBusinessProfilePage.body[0].children[0].children[5].children[7].children[0]",
                            name: "Button",
                            text: "Save business profile",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

