// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final profilePageHandle =
    ffai.ProjectPageHandle<ProfilePageParams, ProfilePageState>(
      name: "ProfilePage",
      key: "Scaffold_b2q817um",
      route: "profile",
      params: const ProfilePageParams(),
      state: const ProfilePageState(),
      widgets: ProfilePageWidgets.tree,
    );

final class ProfilePageParams {
  const ProfilePageParams();
}

final class ProfilePageState {
  const ProfilePageState();
}

abstract final class ProfilePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_b2q817um",
      type: "Scaffold",
      path: "ProfilePage",
      name: "ProfilePage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_i83enneo",
            type: "AppBar",
            path: "ProfilePage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_eip366t9",
                  type: "Text",
                  path: "ProfilePage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Profile",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_ay141tlq",
            type: "Column",
            path: "ProfilePage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_jvj9lwf9",
                type: "Container",
                path: "ProfilePage.body[0].children[0]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_qfgh25fv",
                    type: "Container",
                    path: "ProfilePage.body[0].children[0].children[0]",
                    name: "EmptyState",
                    componentName: "EmptyState",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_cb96rs5g",
                type: "Container",
                path: "ProfilePage.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_lc74yymm",
                    type: "Column",
                    path: "ProfilePage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_n36nrd4d",
                        type: "Row",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[0]",
                        name: "Row",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_rhyhk83k",
                            type: "Container",
                            path:
                                "ProfilePage.body[0].children[1].children[0].children[0].children[0]",
                            name: "Avatar",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_u1i8g5gi",
                                type: "Text",
                                path:
                                    "ProfilePage.body[0].children[1].children[0].children[0].children[0].children[0]",
                                name: "Avatar Text",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_zk6shc90",
                            type: "Column",
                            path:
                                "ProfilePage.body[0].children[1].children[0].children[0].children[1]",
                            name: "Column",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_48qodqq5",
                                type: "Text",
                                path:
                                    "ProfilePage.body[0].children[1].children[0].children[0].children[1].children[0]",
                                name: "Text",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_nohxy76d",
                                type: "Text",
                                path:
                                    "ProfilePage.body[0].children[1].children[0].children[0].children[1].children[1]",
                                name: "Text",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Divider_cqa6890m",
                        type: "Divider",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[1]",
                        name: "Divider",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_qkooonyu",
                        type: "Text",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[2]",
                        name: "Text",
                        text: "Preferences",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_s4oqo1ve",
                        type: "Text",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[3]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_pp1y8dqd",
                        type: "Text",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[4]",
                        name: "Text",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_du3tpktf",
                        type: "Button",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[5]",
                        name: "Button",
                        text: "Partner Dashboard",
                        triggers: const <String>["ON_TAP"],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_zsspm8zd",
                        type: "Button",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[6]",
                        name: "EnableNotificationsButton",
                        text: "Enable Notifications",
                        triggers: const <String>["ON_TAP"],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_1ey5pjqe",
                        type: "Button",
                        path:
                            "ProfilePage.body[0].children[1].children[0].children[7]",
                        name: "Button",
                        text: "Logout",
                        triggers: const <String>["ON_TAP"],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
