// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final savedPageHandle = ffai.ProjectPageHandle<SavedPageParams, SavedPageState>(
  name: "SavedPage",
  key: "Scaffold_ygicpnxn",
  route: "saved",
  params: const SavedPageParams(),
  state: const SavedPageState(),
  widgets: SavedPageWidgets.tree,
);

final class SavedPageParams {
  const SavedPageParams();
}

final class SavedPageState {
  const SavedPageState();
  ffai.ProjectStateFieldHandle get savedDeals =>
      const ffai.ProjectStateFieldHandle(
        name: "savedDeals",
        key: "i9yxwjvn",
        typeName: "List<DataStruct<MobileSavedListingItem>>",
      );
  ffai.ProjectStateFieldHandle get savedPlanItems =>
      const ffai.ProjectStateFieldHandle(
        name: "savedPlanItems",
        key: "plih2v4e",
        typeName: "List<DataStruct<MobileSavedPlanItem>>",
      );
}

abstract final class SavedPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ygicpnxn",
      type: "Scaffold",
      path: "SavedPage",
      name: "SavedPage",
      triggers: const <String>["ON_INIT_STATE"],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_mgdw0pg2",
            type: "AppBar",
            path: "SavedPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_dwgdpxww",
                  type: "Text",
                  path: "SavedPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Saved",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_quud73am",
            type: "Column",
            path: "SavedPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_nwbfucnt",
                type: "Container",
                path: "SavedPage.body[0].children[0]",
                name: "SectionHeader",
                componentName: "SectionHeader",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_ucjv0gby",
                type: "Container",
                path: "SavedPage.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_y2rlj626",
                    type: "Column",
                    path: "SavedPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_ggs5s3gc",
                        type: "Text",
                        path:
                            "SavedPage.body[0].children[1].children[0].children[0]",
                        name: "Text",
                        text: "Sign in required",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_81ulo1eq",
                        type: "Text",
                        path:
                            "SavedPage.body[0].children[1].children[0].children[1]",
                        name: "Text",
                        text:
                            "Create an account to save plans, deals, and booking requests.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_m768gz4k",
                        type: "Button",
                        path:
                            "SavedPage.body[0].children[1].children[0].children[2]",
                        name: "Button",
                        text: "Sign In",
                        triggers: const <String>["ON_TAP"],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_7ht4psv0",
                type: "ListView",
                path: "SavedPage.body[0].children[2]",
                name: "SavedPlansList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_v07n16px",
                    type: "Container",
                    path: "SavedPage.body[0].children[2].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_fj612so6",
                        type: "Column",
                        path:
                            "SavedPage.body[0].children[2].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_iw3juq1h",
                            type: "Text",
                            path:
                                "SavedPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_hplaocqi",
                            type: "Text",
                            path:
                                "SavedPage.body[0].children[2].children[0].children[0].children[1]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_fqeir46q",
                            type: "Text",
                            path:
                                "SavedPage.body[0].children[2].children[0].children[0].children[2]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_te29ughq",
                type: "ListView",
                path: "SavedPage.body[0].children[3]",
                name: "SavedDealsList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_bsn9bmvv",
                    type: "Container",
                    path: "SavedPage.body[0].children[3].children[0]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_3cqa0bg4",
                        type: "Column",
                        path:
                            "SavedPage.body[0].children[3].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_u5mqatei",
                            type: "Text",
                            path:
                                "SavedPage.body[0].children[3].children[0].children[0].children[0]",
                            name: "Text",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_2s2iqyyu",
                            type: "Text",
                            path:
                                "SavedPage.body[0].children[3].children[0].children[0].children[1]",
                            name: "Text",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
