// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final signInPageHandle = ffai.ProjectPageHandle<SignInPageParams, SignInPageState>(
  name: "SignInPage",
  key: "Scaffold_f7kkzxs2",
  route: "sign-in",
  params: const SignInPageParams(),
  state: const SignInPageState(),
  widgets: SignInPageWidgets.tree,
);

final class SignInPageParams {
  const SignInPageParams();
}

final class SignInPageState {
  const SignInPageState();
  ffai.ProjectStateFieldHandle get displayName =>
      const ffai.ProjectStateFieldHandle(
        name: "displayName",
        key: "h0e7sub4",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get email =>
      const ffai.ProjectStateFieldHandle(
        name: "email",
        key: "tgv5vafk",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get isSignup =>
      const ffai.ProjectStateFieldHandle(
        name: "isSignup",
        key: "9u66igk9",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get password =>
      const ffai.ProjectStateFieldHandle(
        name: "password",
        key: "7kdfktjm",
        typeName: "String",
      );
}

abstract final class SignInPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_f7kkzxs2",
      type: "Scaffold",
      path: "SignInPage",
      name: "SignInPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_43n6oyub",
            type: "AppBar",
            path: "SignInPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_a26aji5m",
                  type: "Text",
                  path: "SignInPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "GoFunMotion",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_gubnb3sj",
            type: "Column",
            path: "SignInPage.body[0]",
            name: "Column",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_x7xyp3ot",
                type: "Container",
                path: "SignInPage.body[0].children[0]",
                name: "SectionHeader",
                componentName: "SectionHeader",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_si44ixoa",
                type: "Container",
                path: "SignInPage.body[0].children[1]",
                name: "Container",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_dgs7emev",
                    type: "Column",
                    path: "SignInPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "TextField_l0gd6sbs",
                        type: "TextField",
                        path: "SignInPage.body[0].children[1].children[0].children[0]",
                        name: "EmailField",
                        text: "Email",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "TextField_xo12pvti",
                        type: "TextField",
                        path: "SignInPage.body[0].children[1].children[0].children[1]",
                        name: "PasswordField",
                        text: "Password",
                        triggers: const <String>[
                          "ON_TEXTFIELD_CHANGE",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_z6039hcg",
                        type: "Button",
                        path: "SignInPage.body[0].children[1].children[0].children[2]",
                        name: "SignInButton",
                        text: "Sign In",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Button_doxx6tkp",
                        type: "Button",
                        path: "SignInPage.body[0].children[1].children[0].children[3]",
                        name: "CreateAccountButton",
                        text: "Create Account",
                        triggers: const <String>[
                          "ON_TAP",
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_qf0tozwb",
                type: "Row",
                path: "SignInPage.body[0].children[2]",
                name: "Row",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Button_6kxik65n",
                    type: "Button",
                    path: "SignInPage.body[0].children[2].children[0]",
                    name: "GoogleSignInButton",
                    text: "Google",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_56js8sdy",
                    type: "Button",
                    path: "SignInPage.body[0].children[2].children[1]",
                    name: "AppleSignInButton",
                    text: "Apple",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_lu8i2hmn",
                type: "Button",
                path: "SignInPage.body[0].children[3]",
                name: "GuestSignInButton",
                text: "Browse without an account",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_bek6zsus",
                type: "Button",
                path: "SignInPage.body[0].children[4]",
                name: "ForgotPasswordButton",
                text: "Forgot Password?",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

