// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class SectionHeaderComponentHandle
    extends
        ffai.ProjectComponentHandle<SectionHeaderParams, SectionHeaderState> {
  SectionHeaderComponentHandle()
    : super(
        name: "SectionHeader",
        key: "Container_g1j1orea",
        params: const SectionHeaderParams(),
        state: const SectionHeaderState(),
        widgets: SectionHeaderWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "eyebrow": ffai.string,
          "subtitle": ffai.string,
          "title": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? eyebrow = ffai.kUnsetComponentArg,
    Object? subtitle = ffai.kUnsetComponentArg,
    Object? title = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(eyebrow)) "eyebrow": eyebrow,
        if (!ffai.isUnsetComponentArg(subtitle)) "subtitle": subtitle,
        if (!ffai.isUnsetComponentArg(title)) "title": title,
      },
    );
  }
}

final class SectionHeaderParams {
  const SectionHeaderParams();
  ffai.ProjectParamHandle get eyebrow => const ffai.ProjectParamHandle(
    name: "eyebrow",
    key: "9q246qmr",
    typeName: "String",
  );
  ffai.ProjectParamHandle get subtitle => const ffai.ProjectParamHandle(
    name: "subtitle",
    key: "qg6xm08n",
    typeName: "String",
  );
  ffai.ProjectParamHandle get title => const ffai.ProjectParamHandle(
    name: "title",
    key: "52mguqjm",
    typeName: "String",
  );
}

final class SectionHeaderState {
  const SectionHeaderState();
}

abstract final class SectionHeaderWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_g1j1orea",
      type: "Container",
      path: "SectionHeader",
      name: "SectionHeader",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Column_f9ljv675",
          type: "Column",
          path: "SectionHeader.children[0]",
          name: "Column",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Text_3ijjkjog",
              type: "Text",
              path: "SectionHeader.children[0].children[0]",
              name: "Text",
            ),
            ffai.ProjectWidgetHandle(
              key: "Text_qc410v0u",
              type: "Text",
              path: "SectionHeader.children[0].children[1]",
              name: "Text",
            ),
            ffai.ProjectWidgetHandle(
              key: "Text_kxqdxb04",
              type: "Text",
              path: "SectionHeader.children[0].children[2]",
              name: "Text",
            ),
          ],
        ),
      ],
    ),
  );
}
