// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class WorkspaceEmptyStateComponentHandle extends ffai.ProjectComponentHandle<WorkspaceEmptyStateParams, WorkspaceEmptyStateState> {
  WorkspaceEmptyStateComponentHandle()
    : super(
        name: "WorkspaceEmptyState",
        key: "Container_9lcty62p",
        params: const WorkspaceEmptyStateParams(),
        state: const WorkspaceEmptyStateState(),
        widgets: WorkspaceEmptyStateWidgets.tree,
        paramTypes: <String, ffai.DslType>{
          "label": ffai.string,
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
    Object? label = ffai.kUnsetComponentArg,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
        if (!ffai.isUnsetComponentArg(label)) "label": label,
      },
    );
  }
}

final class WorkspaceEmptyStateParams {
  const WorkspaceEmptyStateParams();
  ffai.ProjectParamHandle get label =>
      const ffai.ProjectParamHandle(
        name: "label",
        key: "2q4jw5rb",
        typeName: "String",
      );
}

final class WorkspaceEmptyStateState {
  const WorkspaceEmptyStateState();
}

abstract final class WorkspaceEmptyStateWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_9lcty62p",
      type: "Container",
      path: "WorkspaceEmptyState",
      name: "WorkspaceEmptyState",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Container_19xq4fr6",
          type: "Container",
          path: "WorkspaceEmptyState.children[0]",
          name: "WorkspaceEmptyStateSurface",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Column_ouq00hoz",
              type: "Column",
              path: "WorkspaceEmptyState.children[0].children[0]",
              name: "Column",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_i5vii9hj",
                  type: "Container",
                  path: "WorkspaceEmptyState.children[0].children[0].children[0]",
                  name: "Container",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Icon_ox917vtt",
                      type: "Icon",
                      path: "WorkspaceEmptyState.children[0].children[0].children[0].children[0]",
                      name: "Icon",
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Text_p3eqfa9v",
                  type: "Text",
                  path: "WorkspaceEmptyState.children[0].children[0].children[1]",
                  name: "Text",
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

